(defvar forest-model (quote 

(((12 14)
  (ROOT
   ("United-States" ("A" ("United-States") (87) ("<=50K") (0))
    ("B" ("United-States") (2) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("South" ("A" ("South") (1) ("<=50K") (0)))
   ("Canada" ("A" ("Canada") (1) ("<=50K") (0)))
   ("Mexico" ("A" ("Mexico") (3) ("<=50K") (0)))
   ("Philippines" ("A" ("Philippines") (1) ("<=50K") (0)))
   ("Italy" ("A" ("Italy") (2) ("<=50K") (0)))
   ("Greece" ("A" ("Greece") (1) ("<=50K") (0)))
   ("Cuba" ("A" ("Cuba") (1) ("<=50K") (0)))))
 ((14 3)
  (ROOT
   ("B" ("United-States" ("United-States") (27) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (32) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0)))
   ("D" ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("United-States" ("United-States") (11) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (25) ("<=50K") (0)))))
 ((4 5)
  (ROOT
   ("A" ("11th" ("United-States") (3) ("<=50K") (0))
    ("9th" ("United-States") (2) ("<=50K") (0))
    ("5th-6th" ("Mexico") (1) ("<=50K") (0))
    ("7th-8th" ("United-States") (3) ("<=50K") (1))
    ("10th" ("United-States") (1) ("<=50K") (0))
    ("12th" ("United-States") (1) ("<=50K") (0)))
   ("C" ("Assoc-voc" ("United-States") (9) ("<=50K") (0))
    ("Some-college" ("United-States") (18) ("<=50K") (0))
    ("Assoc-acdm" ("United-States") (1) ("<=50K") (0)))
   ("B" ("HS-grad" ("United-States") (31) ("<=50K") (3)))
   ("D" ("Prof-school" ("United-States") (1) ("<=50K") (0))
    ("Bachelors" ("United-States") (17) ("<=50K") (3))
    ("Masters" ("India") (1) ("<=50K") (3))
    ("Doctorate" ("United-States") (1) ("<=50K") (0)))))
 ((9 11)
  (ROOT
   ("A" ("White" ("United-States") (72) ("<=50K") (6))
    ("Asian-Pac-Islander" ("South") (1) ("<=50K") (2))
    ("Black" ("United-States") (5) ("<=50K") (0))
    ("Amer-Indian-Eskimo" ("United-States") (1) ("<=50K") (0)))
   ("D" ("White" ("United-States") (9) ("<=50K") (0))
    ("Other" ("United-States") (1) ("<=50K") (0)))
   ("B" ("White" ("United-States") (1) ("<=50K") (0))
    ("Asian-Pac-Islander" ("India") (1) ("<=50K") (0)))
   ("C" ("White" ("United-States") (1) ("<=50K") (0)))))
 ((14 12 11)
  (ROOT ("D" ("A" ("United-States" ("United-States") (4) ("<=50K") (0))))
   ("A"
    ("A" ("United-States" ("United-States") (76) ("<=50K") (0))
     ("South" ("South") (1) ("<=50K") (0))
     ("Philippines" ("Philippines") (2) ("<=50K") (0))
     ("India" ("India") (1) ("<=50K") (0))
     ("China" ("China") (1) ("<=50K") (0))
     ("Thailand" ("Thailand") (1) ("<=50K") (0))
     ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
     ("Mexico" ("Mexico") (1) ("<=50K") (0)))
    ("B" ("United-States" ("United-States") (2) ("<=50K") (0)))
    ("C" ("United-States" ("United-States") (1) ("<=50K") (0)))
    ("D" ("United-States" ("United-States") (2) ("<=50K") (0))))
   ("B" ("A" ("United-States" ("United-States") (6) ("<=50K") (0))))
   ("C" ("A" ("United-States" ("United-States") (1) ("<=50K") (0))))))
 ((1 13)
  (ROOT
   ("C" ("A" ("Peru") (1) ("<=50K") (13)) ("C" ("Germany") (1) ("<=50K") (9))
    ("D" ("United-States") (10) ("<=50K") (0))
    ("B" ("United-States") (11) ("<=50K") (0)))
   ("D" ("B" ("United-States") (9) ("<=50K") (0))
    ("A" ("United-States") (4) ("<=50K") (0))
    ("D" ("United-States") (6) ("<=50K") (0))
    ("C" ("United-States") (7) ("<=50K") (2)))
   ("A" ("C" ("El-Salvador") (1) ("<=50K") (4))
    ("B" ("United-States") (6) ("<=50K") (1))
    ("A" ("United-States") (11) ("<=50K") (0))
    ("D" ("United-States") (3) ("<=50K") (1)))))
 ((13 1)
  (ROOT
   ("D" ("C" ("United-States") (21) ("<=50K") (1))
    ("D" ("United-States") (4) ("<=50K") (0))
    ("A" ("United-States") (6) ("<=50K") (0)))
   ("B" ("C" ("United-States") (10) ("<=50K") (0))
    ("A" ("United-States") (5) ("<=50K") (1))
    ("D" ("United-States") (10) ("<=50K") (2)))
   ("A" ("A" ("Greece") (1) ("<=50K") (7))
    ("C" ("United-States") (12) ("<=50K") (0))
    ("D" ("United-States") (3) ("<=50K") (0)))
   ("C" ("C" ("United-States") (7) ("<=50K") (0))
    ("A" ("United-States") (2) ("<=50K") (0))
    ("D" ("United-States") (8) ("<=50K") (0)))))
 ((14 11)
  (ROOT
   ("A" ("United-States" ("United-States") (86) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Columbia" ("Columbia") (1) ("<=50K") (0))
    ("Haiti" ("Haiti") (1) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0))
    ("South" ("South") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (3) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (1) ("<=50K") (0)))))
 ((10 11 14)
  (ROOT
   ("United-States"
    ("A" ("Male" ("United-States") (60) ("<=50K") (0))
     ("Female" ("United-States") (29) ("<=50K") (0)))
    ("C" ("Male" ("United-States") (3) ("<=50K") (0)))
    ("B" ("Female" ("United-States") (1) ("<=50K") (0)))
    ("D" ("Male" ("United-States") (3) ("<=50K") (0))))
   ("Japan" ("B" ("Male" ("Japan") (1) ("<=50K") (0))))
   ("Dominican-Republic"
    ("A" ("Female" ("Dominican-Republic") (1) ("<=50K") (0))))
   ("Mexico" ("A" ("Male" ("Mexico") (1) ("<=50K") (0))))
   ("Columbia" ("B" ("Male" ("Columbia") (1) ("<=50K") (0))))))
 ((14 12)
  (ROOT
   ("A" ("Cambodia" ("Cambodia") (1) ("<=50K") (0))
    ("United-States" ("United-States") (87) ("<=50K") (0))
    ("Vietnam" ("Vietnam") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("China" ("China") (1) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (3) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0)))))
 ((14 2)
  (ROOT
   ("Private" ("United-States" ("United-States") (68) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0)))
   ("Self-emp-not-inc" ("United-States" ("United-States") (17) ("<=50K") (0)))
   ("State-gov" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("Self-emp-inc" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("Federal-gov" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("Local-gov" ("United-States" ("United-States") (5) ("<=50K") (0)))))
 ((14 1)
  (ROOT ("A" ("United-States" ("United-States") (17) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (27) ("<=50K") (0))
    ("Peru" ("Peru") (1) ("<=50K") (0)) ("Japan" ("Japan") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (20) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
    ("Cambodia" ("Cambodia") (1) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (24) ("<=50K") (0))
    ("Mexico" ("Mexico") (3) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0)))))
 ((4 14)
  (ROOT ("Iran" ("Bachelors" ("Iran") (1) ("<=50K") (0)))
   ("United-States" ("7th-8th" ("United-States") (1) ("<=50K") (0))
    ("HS-grad" ("United-States") (29) ("<=50K") (0))
    ("Some-college" ("United-States") (22) ("<=50K") (0))
    ("10th" ("United-States") (2) ("<=50K") (0))
    ("9th" ("United-States") (2) ("<=50K") (0))
    ("Prof-school" ("United-States") (3) ("<=50K") (0))
    ("11th" ("United-States") (3) ("<=50K") (0))
    ("Bachelors" ("United-States") (13) ("<=50K") (0))
    ("Assoc-voc" ("United-States") (3) ("<=50K") (0))
    ("Masters" ("United-States") (7) ("<=50K") (0))
    ("Doctorate" ("United-States") (1) ("<=50K") (0))
    ("Assoc-acdm" ("United-States") (1) ("<=50K") (0)))
   ("Mexico" ("10th" ("Mexico") (1) ("<=50K") (0))
    ("HS-grad" ("Mexico") (1) ("<=50K") (0))
    ("Some-college" ("Mexico") (1) ("<=50K") (0))
    ("5th-6th" ("Mexico") (1) ("<=50K") (0)))
   ("Columbia" ("HS-grad" ("Columbia") (2) ("<=50K") (0)))
   ("China" ("Bachelors" ("China") (1) ("<=50K") (0)))
   ("Greece" ("Some-college" ("Greece") (1) ("<=50K") (0)))
   ("Dominican-Republic" ("7th-8th" ("Dominican-Republic") (1) ("<=50K") (0))
    ("Some-college" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("Germany" ("HS-grad" ("Germany") (1) ("<=50K") (0)))
   ("Philippines" ("Some-college" ("Philippines") (1) ("<=50K") (0)))))
 ((9 8 14)
  (ROOT ("Mexico" ("Husband" ("White" ("Mexico") (1) ("<=50K") (0))))
   ("United-States"
    ("Not-in-family" ("White" ("United-States") (19) ("<=50K") (0))
     ("Asian-Pac-Islander" ("United-States") (1) ("<=50K") (0))
     ("Black" ("United-States") (2) ("<=50K") (0)))
    ("Husband" ("White" ("United-States") (35) ("<=50K") (0))
     ("Black" ("United-States") (2) ("<=50K") (0)))
    ("Unmarried" ("Black" ("United-States") (4) ("<=50K") (0))
     ("White" ("United-States") (10) ("<=50K") (0)))
    ("Own-child" ("White" ("United-States") (14) ("<=50K") (0))
     ("Black" ("United-States") (1) ("<=50K") (0)))
    ("Other-relative" ("White" ("United-States") (4) ("<=50K") (0)))
    ("Wife" ("White" ("United-States") (1) ("<=50K") (0))))
   ("El-Salvador"
    ("Not-in-family" ("White" ("El-Salvador") (1) ("<=50K") (0))))
   ("England" ("Not-in-family" ("White" ("England") (2) ("<=50K") (0))))
   ("Thailand" ("Own-child" ("White" ("Thailand") (1) ("<=50K") (0))))
   ("Iran" ("Husband" ("Asian-Pac-Islander" ("Iran") (1) ("<=50K") (0)))
    ("Not-in-family" ("White" ("Iran") (1) ("<=50K") (0))))))
 ((2 11)
  (ROOT
   ("A" ("Private" ("Vietnam") (1) ("<=50K") (68))
    ("Self-emp-not-inc" ("United-States") (4) ("<=50K") (0))
    ("Local-gov" ("United-States") (7) ("<=50K") (0))
    ("Self-emp-inc" ("United-States") (4) ("<=50K") (0))
    ("State-gov" ("United-States") (3) ("<=50K") (1))
    ("Federal-gov" ("United-States") (2) ("<=50K") (0)))
   ("D" ("Private" ("United-States") (5) ("<=50K") (0)))
   ("C" ("Self-emp-inc" ("United-States") (1) ("<=50K") (0))
    ("Local-gov" ("United-States") (1) ("<=50K") (0))
    ("Private" ("United-States") (2) ("<=50K") (0)))
   ("B" ("Private" ("United-States") (1) ("<=50K") (0)))))
 ((14 13)
  (ROOT
   ("A" ("United-States" ("United-States") (24) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (44) ("<=50K") (0))
    ("Greece" ("Greece") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Cambodia" ("Cambodia") (1) ("<=50K") (0))
    ("Peru" ("Peru") (1) ("<=50K") (0))
    ("Scotland" ("Scotland") (1) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (22) ("<=50K") (0))
    ("Hungary" ("Hungary") (1) ("<=50K") (0)))))
 ((8 12)
  (ROOT
   ("A" ("Unmarried" ("United-States") (13) ("<=50K") (0))
    ("Wife" ("United-States") (3) ("<=50K") (1))
    ("Not-in-family" ("United-States") (18) ("<=50K") (1))
    ("Husband" ("Mexico") (1) ("<=50K") (44))
    ("Own-child" ("Mexico") (1) ("<=50K") (13))
    ("Other-relative" ("United-States") (2) ("<=50K") (0)))
   ("C" ("Husband" ("United-States") (3) ("<=50K") (0)))))
 ((14 2)
  (ROOT
   ("Federal-gov" ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("United-States" ("United-States") (1) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0)))
   ("Private" ("United-States" ("United-States") (72) ("<=50K") (0))
    ("Cuba" ("Cuba") (2) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("Self-emp-not-inc" ("United-States" ("United-States") (9) ("<=50K") (0)))
   ("Local-gov" ("United-States" ("United-States") (6) ("<=50K") (0))
    ("Outlying-US(Guam-USVI-etc)" ("Outlying-US(Guam-USVI-etc)") (1) ("<=50K")
     (0)))
   ("Self-emp-inc" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("State-gov" ("United-States" ("United-States") (4) ("<=50K") (0)))))
 ((9 3 14)
  (ROOT
   ("United-States"
    ("A" ("Asian-Pac-Islander" ("United-States") (1) ("<=50K") (0))
     ("Black" ("United-States") (1) ("<=50K") (0))
     ("White" ("United-States") (20) ("<=50K") (0)))
    ("C" ("White" ("United-States") (22) ("<=50K") (0))
     ("Black" ("United-States") (3) ("<=50K") (0)))
    ("B" ("White" ("United-States") (20) ("<=50K") (0))
     ("Black" ("United-States") (1) ("<=50K") (0))
     ("Asian-Pac-Islander" ("United-States") (1) ("<=50K") (0)))
    ("D" ("White" ("United-States") (19) ("<=50K") (0))
     ("Black" ("United-States") (2) ("<=50K") (0))))
   ("Yugoslavia" ("B" ("White" ("Yugoslavia") (1) ("<=50K") (0))))
   ("Philippines"
    ("B" ("Asian-Pac-Islander" ("Philippines") (1) ("<=50K") (0))))
   ("Mexico" ("C" ("White" ("Mexico") (1) ("<=50K") (0)))
    ("D" ("White" ("Mexico") (2) ("<=50K") (0)))
    ("B" ("White" ("Mexico") (1) ("<=50K") (0))))
   ("Poland" ("C" ("White" ("Poland") (1) ("<=50K") (0))))
   ("Canada" ("B" ("White" ("Canada") (1) ("<=50K") (0))))
   ("Honduras" ("D" ("White" ("Honduras") (1) ("<=50K") (0))))
   ("Vietnam" ("B" ("Asian-Pac-Islander" ("Vietnam") (1) ("<=50K") (0))))))
 ((14 12 11)
  (ROOT
   ("A"
    ("C" ("South" ("South") (1) ("<=50K") (0))
     ("United-States" ("United-States") (4) ("<=50K") (0)))
    ("A" ("United-States" ("United-States") (82) ("<=50K") (0))
     ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
     ("Mexico" ("Mexico") (1) ("<=50K") (0))
     ("Cuba" ("Cuba") (3) ("<=50K") (0))
     ("Canada" ("Canada") (1) ("<=50K") (0))
     ("Hong" ("Hong") (1) ("<=50K") (0))
     ("Germany" ("Germany") (1) ("<=50K") (0))
     ("Haiti" ("Haiti") (1) ("<=50K") (0))
     ("Italy" ("Italy") (1) ("<=50K") (0))))
   ("B" ("A" ("United-States" ("United-States") (1) ("<=50K") (0))))
   ("D" ("A" ("United-States" ("United-States") (1) ("<=50K") (0))))
   ("C" ("A" ("United-States" ("United-States") (1) ("<=50K") (0))))))
 ((12 10)
  (ROOT
   ("Female" ("A" ("United-States") (36) ("<=50K") (1))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("Male" ("A" ("Mexico") (3) ("<=50K") (56))
    ("B" ("United-States") (1) ("<=50K") (0))
    ("D" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))))
 ((9 14)
  (ROOT
   ("United-States" ("White" ("United-States") (77) ("<=50K") (0))
    ("Black" ("United-States") (8) ("<=50K") (0)))
   ("Mexico" ("White" ("Mexico") (1) ("<=50K") (0)))
   ("India" ("Asian-Pac-Islander" ("India") (3) ("<=50K") (0)))
   ("Canada" ("White" ("Canada") (1) ("<=50K") (0)))
   ("Portugal" ("White" ("Portugal") (1) ("<=50K") (0)))
   ("Dominican-Republic" ("White" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("Philippines" ("Asian-Pac-Islander" ("Philippines") (1) ("<=50K") (0))
    ("White" ("Philippines") (1) ("<=50K") (0)))
   ("Columbia" ("White" ("Columbia") (1) ("<=50K") (0)))
   ("Puerto-Rico" ("Other" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("China" ("Asian-Pac-Islander" ("China") (1) ("<=50K") (0)))
   ("Japan" ("Asian-Pac-Islander" ("Japan") (1) ("<=50K") (0)))
   ("Iran" ("White" ("Iran") (1) ("<=50K") (0)))
   ("Germany" ("White" ("Germany") (1) ("<=50K") (0)))))
 ((12 5 11)
  (ROOT
   ("A"
    ("C" ("A" ("United-States") (30) ("<=50K") (0))
     ("C" ("United-States") (1) ("<=50K") (0)))
    ("D" ("A" ("United-States") (15) ("<=50K") (2))
     ("C" ("United-States") (5) ("<=50K") (0))
     ("B" ("United-States") (3) ("<=50K") (0)))
    ("B" ("A" ("United-States") (25) ("<=50K") (0))
     ("C" ("United-States") (1) ("<=50K") (0)))
    ("A" ("A" ("United-States") (6) ("<=50K") (3))))
   ("D" ("C" ("A" ("United-States") (1) ("<=50K") (0)))
    ("B" ("A" ("United-States") (2) ("<=50K") (0)))
    ("D" ("A" ("United-States") (3) ("<=50K") (0))))
   ("B" ("C" ("A" ("United-States") (1) ("<=50K") (0))))
   ("C" ("C" ("A" ("United-States") (1) ("<=50K") (0)))
    ("D" ("A" ("United-States") (1) ("<=50K") (0))))))
 ((11 14 12)
  (ROOT
   ("A"
    ("United-States" ("A" ("United-States") (78) ("<=50K") (0))
     ("B" ("United-States") (3) ("<=50K") (0))
     ("D" ("United-States") (5) ("<=50K") (0))
     ("C" ("United-States") (2) ("<=50K") (0)))
    ("Jamaica" ("A" ("Jamaica") (1) ("<=50K") (0)))
    ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0)))
    ("Philippines" ("A" ("Philippines") (2) ("<=50K") (0)))
    ("Cuba" ("A" ("Cuba") (1) ("<=50K") (0)) ("D" ("Cuba") (1) ("<=50K") (0)))
    ("Poland" ("A" ("Poland") (1) ("<=50K") (0))))
   ("C" ("United-States" ("A" ("United-States") (3) ("<=50K") (0))))
   ("D" ("United-States" ("A" ("United-States") (1) ("<=50K") (0))))
   ("B" ("United-States" ("A" ("United-States") (1) ("<=50K") (0))))))
 ((12 6)
  (ROOT
   ("Married-civ-spouse" ("A" ("United-States") (34) ("<=50K") (4))
    ("C" ("United-States") (2) ("<=50K") (0))
    ("D" ("United-States") (1) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("Married-spouse-absent" ("A" ("United-States") (1) ("<=50K") (0)))
   ("Never-married" ("A" ("United-States") (33) ("<=50K") (3)))
   ("Divorced" ("A" ("United-States") (16) ("<=50K") (1)))
   ("Widowed" ("A" ("United-States") (3) ("<=50K") (0)))
   ("Separated" ("A" ("United-States") (1) ("<=50K") (0)))))
 ((10 11)
  (ROOT
   ("A" ("Male" ("South") (1) ("<=50K") (53))
    ("Female" ("Philippines") (2) ("<=50K") (32)))
   ("B" ("Male" ("Guatemala") (1) ("<=50K") (3)))
   ("D" ("Female" ("United-States") (2) ("<=50K") (0))
    ("Male" ("United-States") (5) ("<=50K") (0)))
   ("C" ("Male" ("Cuba") (1) ("<=50K") (0)))))
 ((12 10 14)
  (ROOT
   ("United-States"
    ("Male" ("A" ("United-States") (57) ("<=50K") (0))
     ("C" ("United-States") (1) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0)))
    ("Female" ("A" ("United-States") (28) ("<=50K") (0))
     ("B" ("United-States") (1) ("<=50K") (0))))
   ("Columbia" ("Female" ("A" ("Columbia") (1) ("<=50K") (0)))
    ("Male" ("A" ("Columbia") (2) ("<=50K") (0))))
   ("Puerto-Rico" ("Female" ("A" ("Puerto-Rico") (1) ("<=50K") (0))))
   ("Mexico" ("Male" ("A" ("Mexico") (1) ("<=50K") (0)))
    ("Female" ("A" ("Mexico") (1) ("<=50K") (0))))
   ("Japan" ("Male" ("A" ("Japan") (1) ("<=50K") (0)))
    ("Female" ("A" ("Japan") (1) ("<=50K") (0))))
   ("Germany" ("Female" ("A" ("Germany") (1) ("<=50K") (0))))
   ("South" ("Male" ("A" ("South") (1) ("<=50K") (0))))
   ("Guatemala" ("Male" ("A" ("Guatemala") (1) ("<=50K") (0))))
   ("Jamaica" ("Female" ("A" ("Jamaica") (1) ("<=50K") (0))))))
 ((12 14 5)
  (ROOT
   ("B" ("United-States" ("A" ("United-States") (41) ("<=50K") (0)))
    ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0)))
    ("Canada" ("A" ("Canada") (1) ("<=50K") (0)))
    ("El-Salvador" ("A" ("El-Salvador") (1) ("<=50K") (0))))
   ("D"
    ("United-States" ("A" ("United-States") (19) ("<=50K") (0))
     ("C" ("United-States") (2) ("<=50K") (0)))
    ("Japan" ("A" ("Japan") (1) ("<=50K") (0)))
    ("England" ("A" ("England") (1) ("<=50K") (0)))
    ("Iran" ("A" ("Iran") (1) ("<=50K") (0))))
   ("C" ("United-States" ("A" ("United-States") (19) ("<=50K") (0)))
    ("Philippines" ("A" ("Philippines") (1) ("<=50K") (0)))
    ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0))))
   ("A" ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0)))
    ("United-States" ("A" ("United-States") (10) ("<=50K") (0))))))
 ((14 5)
  (ROOT
   ("A" ("Cambodia" ("Cambodia") (1) ("<=50K") (0))
    ("United-States" ("United-States") (15) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Yugoslavia" ("Yugoslavia") (1) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (19) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (33) ("<=50K") (0))
    ("Vietnam" ("Vietnam") (1) ("<=50K") (0))
    ("Ireland" ("Ireland") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (24) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))))
 ((13 5)
  (ROOT
   ("A" ("D" ("United-States") (3) ("<=50K") (1))
    ("A" ("Puerto-Rico") (1) ("<=50K") (5))
    ("C" ("United-States") (8) ("<=50K") (1)))
   ("C" ("C" ("United-States") (11) ("<=50K") (1))
    ("A" ("United-States") (4) ("<=50K") (1))
    ("D" ("United-States") (7) ("<=50K") (0)))
   ("B" ("C" ("United-States") (11) ("<=50K") (3))
    ("A" ("United-States") (3) ("<=50K") (1))
    ("D" ("United-States") (10) ("<=50K") (0)))
   ("D" ("C" ("United-States") (8) ("<=50K") (1))
    ("D" ("United-States") (13) ("<=50K") (1))
    ("A" ("Outlying-US(Guam-USVI-etc)") (1) ("<=50K") (5)))))
 ((5 14)
  (ROOT ("Greece" ("D" ("Greece") (1) ("<=50K") (0)))
   ("United-States" ("C" ("United-States") (30) ("<=50K") (0))
    ("D" ("United-States") (18) ("<=50K") (0))
    ("B" ("United-States") (33) ("<=50K") (0))
    ("A" ("United-States") (7) ("<=50K") (0)))
   ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0))
    ("C" ("Mexico") (2) ("<=50K") (0)) ("B" ("Mexico") (2) ("<=50K") (0)))
   ("Columbia" ("D" ("Columbia") (1) ("<=50K") (0)))
   ("Thailand" ("B" ("Thailand") (1) ("<=50K") (0)))
   ("England" ("D" ("England") (1) ("<=50K") (0)))
   ("South" ("B" ("South") (1) ("<=50K") (0)))
   ("Puerto-Rico" ("B" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("China" ("D" ("China") (1) ("<=50K") (0)))))
 ((11 14 12)
  (ROOT
   ("A"
    ("United-States" ("D" ("United-States") (4) ("<=50K") (0))
     ("A" ("United-States") (76) ("<=50K") (0))
     ("C" ("United-States") (3) ("<=50K") (0))
     ("B" ("United-States") (1) ("<=50K") (0)))
    ("Ecuador" ("A" ("Ecuador") (1) ("<=50K") (0)))
    ("Greece" ("A" ("Greece") (1) ("<=50K") (0)))
    ("Dominican-Republic" ("A" ("Dominican-Republic") (1) ("<=50K") (0)))
    ("Portugal" ("A" ("Portugal") (1) ("<=50K") (0)))
    ("Germany" ("A" ("Germany") (1) ("<=50K") (0)))
    ("India" ("A" ("India") (1) ("<=50K") (0)))
    ("Mexico" ("A" ("Mexico") (3) ("<=50K") (0)))
    ("Guatemala" ("A" ("Guatemala") (1) ("<=50K") (0)))
    ("Italy" ("A" ("Italy") (1) ("<=50K") (0))))
   ("C" ("United-States" ("A" ("United-States") (5) ("<=50K") (0))))))
 ((10 14)
  (ROOT
   ("United-States" ("Male" ("United-States") (68) ("<=50K") (0))
    ("Female" ("United-States") (24) ("<=50K") (0)))
   ("Cuba" ("Female" ("Cuba") (1) ("<=50K") (0)))
   ("Canada" ("Male" ("Canada") (1) ("<=50K") (0)))
   ("Taiwan" ("Male" ("Taiwan") (1) ("<=50K") (0)))
   ("Mexico" ("Female" ("Mexico") (1) ("<=50K") (0)))
   ("Laos" ("Male" ("Laos") (1) ("<=50K") (0)))
   ("Germany" ("Female" ("Germany") (1) ("<=50K") (0)))
   ("Iran" ("Male" ("Iran") (1) ("<=50K") (0)))
   ("Columbia" ("Male" ("Columbia") (1) ("<=50K") (0)))))
 ((11 14)
  (ROOT ("Mexico" ("A" ("Mexico") (5) ("<=50K") (0)))
   ("United-States" ("A" ("United-States") (82) ("<=50K") (0))
    ("D" ("United-States") (6) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("Poland" ("A" ("Poland") (1) ("<=50K") (0)))
   ("Guatemala" ("A" ("Guatemala") (1) ("<=50K") (0)))
   ("Jamaica" ("A" ("Jamaica") (2) ("<=50K") (0)))
   ("Thailand" ("A" ("Thailand") (1) ("<=50K") (0)))
   ("Canada" ("A" ("Canada") (1) ("<=50K") (0)))))
 ((13 14)
  (ROOT
   ("United-States" ("C" ("United-States") (39) ("<=50K") (0))
    ("D" ("United-States") (33) ("<=50K") (0))
    ("A" ("United-States") (16) ("<=50K") (0)))
   ("Philippines" ("C" ("Philippines") (2) ("<=50K") (0)))
   ("Canada" ("A" ("Canada") (1) ("<=50K") (0)))
   ("France" ("D" ("France") (1) ("<=50K") (0))
    ("C" ("France") (1) ("<=50K") (0)))
   ("Mexico" ("A" ("Mexico") (2) ("<=50K") (0))
    ("C" ("Mexico") (1) ("<=50K") (0)) ("D" ("Mexico") (2) ("<=50K") (0)))
   ("England" ("D" ("England") (1) ("<=50K") (0)))
   ("Ecuador" ("A" ("Ecuador") (1) ("<=50K") (0)))))
 ((14 9 6)
  (ROOT
   ("Never-married"
    ("White" ("United-States" ("United-States") (24) ("<=50K") (0))
     ("Ireland" ("Ireland") (1) ("<=50K") (0)))
    ("Black" ("United-States" ("United-States") (1) ("<=50K") (0)))
    ("Asian-Pac-Islander" ("Japan" ("Japan") (1) ("<=50K") (0))))
   ("Married-civ-spouse"
    ("White" ("United-States" ("United-States") (41) ("<=50K") (0))
     ("Mexico" ("Mexico") (1) ("<=50K") (0)))
    ("Asian-Pac-Islander" ("Hong" ("Hong") (1) ("<=50K") (0))
     ("Philippines" ("Philippines") (1) ("<=50K") (0))
     ("United-States" ("United-States") (1) ("<=50K") (0)))
    ("Black" ("United-States" ("United-States") (1) ("<=50K") (0))))
   ("Divorced"
    ("White" ("United-States" ("United-States") (12) ("<=50K") (0))
     ("England" ("England") (1) ("<=50K") (0))
     ("Mexico" ("Mexico") (1) ("<=50K") (0)))
    ("Black" ("United-States" ("United-States") (3) ("<=50K") (0)))
    ("Asian-Pac-Islander"
     ("United-States" ("United-States") (1) ("<=50K") (0))))
   ("Separated"
    ("White" ("United-States" ("United-States") (2) ("<=50K") (0))
     ("Peru" ("Peru") (1) ("<=50K") (0)))
    ("Black" ("United-States" ("United-States") (1) ("<=50K") (0))))
   ("Widowed" ("White" ("United-States" ("United-States") (2) ("<=50K") (0))))
   ("Married-spouse-absent"
    ("White" ("United-States" ("United-States") (1) ("<=50K") (0))
     ("Mexico" ("Mexico") (1) ("<=50K") (0)))
    ("Black" ("Jamaica" ("Jamaica") (1) ("<=50K") (0))))))
 ((13 1)
  (ROOT
   ("D" ("C" ("United-States") (8) ("<=50K") (1))
    ("A" ("United-States") (7) ("<=50K") (0))
    ("D" ("United-States") (11) ("<=50K") (0)))
   ("A" ("C" ("United-States") (7) ("<=50K") (0))
    ("A" ("United-States") (13) ("<=50K") (1))
    ("D" ("United-States") (3) ("<=50K") (1)))
   ("B" ("D" ("United-States") (10) ("<=50K") (0))
    ("C" ("United-States") (9) ("<=50K") (2))
    ("A" ("United-States") (1) ("<=50K") (0)))
   ("C" ("D" ("United-States") (9) ("<=50K") (1))
    ("C" ("United-States") (12) ("<=50K") (2))
    ("A" ("United-States") (2) ("<=50K") (0)))))
 ((9 3)
  (ROOT
   ("B" ("White" ("United-States") (20) ("<=50K") (0))
    ("Black" ("United-States") (3) ("<=50K") (0))
    ("Asian-Pac-Islander" ("United-States") (1) ("<=50K") (0)))
   ("A" ("White" ("United-States") (23) ("<=50K") (2))
    ("Asian-Pac-Islander" ("China") (1) ("<=50K") (4))
    ("Black" ("United-States") (1) ("<=50K") (0)))
   ("D" ("White" ("United-States") (18) ("<=50K") (2))
    ("Black" ("United-States") (2) ("<=50K") (0)))
   ("C" ("White" ("United-States") (15) ("<=50K") (3))
    ("Black" ("United-States") (4) ("<=50K") (0))
    ("Other" ("United-States") (1) ("<=50K") (0)))))
 ((14 9)
  (ROOT
   ("White" ("United-States" ("United-States") (79) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (4) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (2) ("<=50K") (0))
    ("Greece" ("Greece") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
    ("Peru" ("Peru") (1) ("<=50K") (0)))
   ("Black" ("United-States" ("United-States") (5) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (2) ("<=50K") (0)))
   ("Asian-Pac-Islander" ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("Other" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("Amer-Indian-Eskimo"
    ("United-States" ("United-States") (1) ("<=50K") (0)))))
 ((11 14)
  (ROOT ("Mexico" ("A" ("Mexico") (3) ("<=50K") (0)))
   ("United-States" ("A" ("United-States") (82) ("<=50K") (0))
    ("D" ("United-States") (2) ("<=50K") (0))
    ("C" ("United-States") (2) ("<=50K") (0)))
   ("Japan" ("A" ("Japan") (2) ("<=50K") (0)))
   ("Vietnam" ("A" ("Vietnam") (1) ("<=50K") (0)))
   ("Puerto-Rico" ("A" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("Trinadad&Tobago" ("A" ("Trinadad&Tobago") (1) ("<=50K") (0)))
   ("Guatemala" ("A" ("Guatemala") (1) ("<=50K") (0)))
   ("Jamaica" ("B" ("Jamaica") (1) ("<=50K") (0))
    ("A" ("Jamaica") (1) ("<=50K") (0)))
   ("Dominican-Republic" ("A" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("India" ("D" ("India") (1) ("<=50K") (0))
    ("A" ("India") (1) ("<=50K") (0)))))
 ((14 12)
  (ROOT
   ("A" ("United-States" ("United-States") (86) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (2) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0))
    ("Greece" ("Greece") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0))
    ("Columbia" ("Columbia") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (4) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (2) ("<=50K") (0)))))
 ((14 11)
  (ROOT
   ("A" ("United-States" ("United-States") (86) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0)) ("Cuba" ("Cuba") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (3) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (1) ("<=50K") (0)))))
 ((14 10)
  (ROOT
   ("Female" ("United-States" ("United-States") (30) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Iran" ("Iran") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("Male" ("Vietnam" ("Vietnam") (1) ("<=50K") (0))
    ("United-States" ("United-States") (59) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0))
    ("South" ("South") (2) ("<=50K") (0)) ("Laos" ("Laos") (1) ("<=50K") (0))
    ("Taiwan" ("Taiwan") (1) ("<=50K") (0))
    ("France" ("France") (1) ("<=50K") (0)))))
 ((13 10)
  (ROOT
   ("Male" ("C" ("United-States") (28) ("<=50K") (1))
    ("D" ("United-States") (27) ("<=50K") (3))
    ("A" ("United-States") (9) ("<=50K") (2)))
   ("Female" ("A" ("United-States") (8) ("<=50K") (1))
    ("C" ("United-States") (16) ("<=50K") (0))
    ("D" ("Puerto-Rico") (1) ("<=50K") (4)))))
 ((5 13)
  (ROOT
   ("C" ("C" ("United-States") (17) ("<=50K") (1))
    ("B" ("United-States") (17) ("<=50K") (2))
    ("A" ("Italy") (1) ("<=50K") (2))
    ("D" ("United-States") (7) ("<=50K") (2)))
   ("A" ("B" ("United-States") (8) ("<=50K") (0))
    ("C" ("United-States") (10) ("<=50K") (0))
    ("D" ("United-States") (2) ("<=50K") (0))
    ("A" ("Dominican-Republic") (1) ("<=50K") (3)))
   ("D" ("D" ("United-States") (12) ("<=50K") (1))
    ("B" ("United-States") (6) ("<=50K") (1))
    ("C" ("United-States") (6) ("<=50K") (1)))))
 ((1 5 14)
  (ROOT
   ("United-States"
    ("C" ("C" ("United-States") (8) ("<=50K") (0))
     ("A" ("United-States") (4) ("<=50K") (0))
     ("B" ("United-States") (13) ("<=50K") (0))
     ("D" ("United-States") (8) ("<=50K") (0)))
    ("D" ("C" ("United-States") (7) ("<=50K") (0))
     ("A" ("United-States") (4) ("<=50K") (0))
     ("D" ("United-States") (4) ("<=50K") (0))
     ("B" ("United-States") (1) ("<=50K") (0)))
    ("B" ("C" ("United-States") (3) ("<=50K") (0))
     ("B" ("United-States") (12) ("<=50K") (0))
     ("D" ("United-States") (8) ("<=50K") (0))
     ("A" ("United-States") (7) ("<=50K") (0)))
    ("A" ("D" ("United-States") (5) ("<=50K") (0))
     ("A" ("United-States") (2) ("<=50K") (0))
     ("C" ("United-States") (2) ("<=50K") (0))
     ("B" ("United-States") (1) ("<=50K") (0))))
   ("Germany"
    ("C" ("D" ("Germany") (1) ("<=50K") (0))
     ("C" ("Germany") (1) ("<=50K") (0))))
   ("Mexico"
    ("A" ("B" ("Mexico") (4) ("<=50K") (0))
     ("A" ("Mexico") (1) ("<=50K") (0))))
   ("Cambodia" ("D" ("C" ("Cambodia") (1) ("<=50K") (0))))
   ("Guatemala" ("C" ("B" ("Guatemala") (1) ("<=50K") (0))))
   ("South" ("A" ("D" ("South") (1) ("<=50K") (0))))
   ("Yugoslavia" ("D" ("B" ("Yugoslavia") (1) ("<=50K") (0))))))
 ((13 1)
  (ROOT
   ("A" ("C" ("United-States") (15) ("<=50K") (3))
    ("A" ("Guatemala") (1) ("<=50K") (7))
    ("D" ("United-States") (3) ("<=50K") (0)))
   ("D" ("D" ("United-States") (7) ("<=50K") (0))
    ("A" ("United-States") (9) ("<=50K") (1))
    ("C" ("United-States") (5) ("<=50K") (2)))
   ("C" ("D" ("United-States") (7) ("<=50K") (0))
    ("C" ("Yugoslavia") (1) ("<=50K") (9))
    ("A" ("United-States") (2) ("<=50K") (0)))
   ("B" ("C" ("United-States") (12) ("<=50K") (2))
    ("D" ("United-States") (11) ("<=50K") (0))
    ("A" ("United-States") (3) ("<=50K") (0)))))
 ((10 1)
  (ROOT
   ("D" ("Male" ("United-States") (11) ("<=50K") (0))
    ("Female" ("United-States") (5) ("<=50K") (2)))
   ("B" ("Male" ("Iran") (1) ("<=50K") (20))
    ("Female" ("United-States") (8) ("<=50K") (0)))
   ("C" ("Male" ("United-States") (17) ("<=50K") (2))
    ("Female" ("United-States") (5) ("<=50K") (0)))
   ("A" ("Female" ("United-States") (12) ("<=50K") (0))
    ("Male" ("United-States") (17) ("<=50K") (0)))))
 ((9 14)
  (ROOT
   ("United-States" ("White" ("United-States") (82) ("<=50K") (0))
    ("Black" ("United-States") (9) ("<=50K") (0))
    ("Amer-Indian-Eskimo" ("United-States") (2) ("<=50K") (0)))
   ("Columbia" ("White" ("Columbia") (1) ("<=50K") (0)))
   ("Ireland" ("White" ("Ireland") (1) ("<=50K") (0)))
   ("Greece" ("White" ("Greece") (1) ("<=50K") (0)))
   ("Mexico" ("White" ("Mexico") (2) ("<=50K") (0)))
   ("Germany" ("White" ("Germany") (1) ("<=50K") (0)))
   ("India" ("Asian-Pac-Islander" ("India") (1) ("<=50K") (0)))))
 ((14 11)
  (ROOT
   ("A" ("United-States" ("United-States") (87) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (5) ("<=50K") (0)))
   ("C" ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (3) ("<=50K") (0)))))) )) 
(defvar results (quote 

(0.9385599 0.9448 0.938 0.937 0.9436 0.9375 0.9408 0.9345 0.9351 0.939 0.9354
 0.937 0.9375 0.9366 0.9385 0.9405 0.9379 0.9399 0.9387 0.9388 0.9401) )) 
;;;;;;;;;;;;;

; Wich features are numeric? 0: not, 1: yes. *(not yet implemented)
(defvar *num-fetures* '(1 3 5 11 12 13))
; Total features *(not yet implemented)
(defvar *total-fetures* '14)
(defvar *min-fetures-sample* '2)
(defvar *max-fetures-sample* '5)
; Targets? 
(defvar *targets* '("<=50K" ">50K"))

; Model parameters.

; Number os trees in the forest:
(defvar *NTrees* 50)
; How much samples will be used to build the trees?
(defvar *NSamples* 100)
; To prune the worst trees with low rating accuracy.
; Prune below THPrec.
(defvar *THPrec* 0.96)

; Test rounds 
(defvar *TRounds* 20)
; Load the datasets to memory
(defvar *TSamples_train* 30000)
(defvar *TSamples_test* 10000)

; 16280 dataset.test.csv
; 32561 dataset.training.csv
; 48841 total
; Without samples with missing data:
; 15059 dataset.test.csv
; 30162 dataset.training.csv
; 45221 total

;EOF