(defvar forest-model (quote 

(((5 14)
  (ROOT
   ("United-States" ("C" ("United-States") (31) ("<=50K") (0))
    ("B" ("United-States") (36) ("<=50K") (0))
    ("D" ("United-States") (14) ("<=50K") (0))
    ("A" ("United-States") (10) ("<=50K") (0)))
   ("Poland" ("A" ("Poland") (1) ("<=50K") (0)))
   ("El-Salvador" ("C" ("El-Salvador") (1) ("<=50K") (0))
    ("A" ("El-Salvador") (1) ("<=50K") (0)))
   ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0)))
   ("India" ("D" ("India") (2) ("<=50K") (0)))
   ("Vietnam" ("C" ("Vietnam") (1) ("<=50K") (0)))
   ("Guatemala" ("A" ("Guatemala") (1) ("<=50K") (0)))
   ("Iran" ("D" ("Iran") (1) ("<=50K") (0)))))
 ((9 14 12)
  (ROOT
   ("A"
    ("United-States" ("White" ("United-States") (73) ("<=50K") (0))
     ("Asian-Pac-Islander" ("United-States") (3) ("<=50K") (0))
     ("Other" ("United-States") (1) ("<=50K") (0))
     ("Black" ("United-States") (7) ("<=50K") (0))
     ("Amer-Indian-Eskimo" ("United-States") (1) ("<=50K") (0)))
    ("Thailand" ("Asian-Pac-Islander" ("Thailand") (1) ("<=50K") (0)))
    ("Jamaica" ("Black" ("Jamaica") (1) ("<=50K") (0)))
    ("Italy" ("White" ("Italy") (2) ("<=50K") (0)))
    ("Haiti" ("Black" ("Haiti") (1) ("<=50K") (0)))
    ("Poland" ("White" ("Poland") (1) ("<=50K") (0)))
    ("Philippines" ("Asian-Pac-Islander" ("Philippines") (1) ("<=50K") (0)))
    ("Mexico" ("White" ("Mexico") (1) ("<=50K") (0))
     ("Other" ("Mexico") (1) ("<=50K") (0)))
    ("El-Salvador" ("White" ("El-Salvador") (1) ("<=50K") (0))))
   ("C" ("United-States" ("White" ("United-States") (3) ("<=50K") (0))))
   ("B" ("United-States" ("White" ("United-States") (1) ("<=50K") (0))))
   ("D" ("United-States" ("White" ("United-States") (1) ("<=50K") (0))))))
 ((1 13)
  (ROOT
   ("A" ("D" ("United-States") (5) ("<=50K") (2))
    ("A" ("United-States") (8) ("<=50K") (0))
    ("C" ("United-States") (2) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("D" ("C" ("United-States") (8) ("<=50K") (1))
    ("B" ("United-States") (11) ("<=50K") (3))
    ("D" ("United-States") (7) ("<=50K") (0))
    ("A" ("United-States") (2) ("<=50K") (0)))
   ("C" ("B" ("United-States") (4) ("<=50K") (1))
    ("C" ("United-States") (14) ("<=50K") (1))
    ("D" ("United-States") (20) ("<=50K") (1))
    ("A" ("United-States") (7) ("<=50K") (2)))))
 ((1 10)
  (ROOT
   ("Male" ("A" ("United-States") (9) ("<=50K") (0))
    ("C" ("United-States") (20) ("<=50K") (2))
    ("D" ("United-States") (18) ("<=50K") (2))
    ("B" ("Puerto-Rico") (2) ("<=50K") (21)))
   ("Female" ("B" ("United-States") (5) ("<=50K") (1))
    ("C" ("United-States") (9) ("<=50K") (1))
    ("A" ("United-States") (6) ("<=50K") (0))
    ("D" ("United-States") (4) ("<=50K") (0)))))
 ((10 13 3)
  (ROOT
   ("C"
    ("A" ("Male" ("United-States") (1) ("<=50K") (0))
     ("Female" ("Mexico") (1) ("<=50K") (2)))
    ("C" ("Male" ("United-States") (4) ("<=50K") (0))
     ("Female" ("United-States") (3) ("<=50K") (0)))
    ("D" ("Male" ("United-States") (6) ("<=50K") (0))))
   ("D"
    ("C" ("Male" ("Canada") (1) ("<=50K") (14))
     ("Female" ("United-States") (4) ("<=50K") (1)))
    ("A" ("Female" ("United-States") (2) ("<=50K") (0))
     ("Male" ("United-States") (2) ("<=50K") (0)))
    ("D" ("Female" ("United-States") (1) ("<=50K") (0))
     ("Male" ("United-States") (8) ("<=50K") (0))))
   ("B"
    ("D" ("Female" ("United-States") (2) ("<=50K") (0))
     ("Male" ("United-States") (5) ("<=50K") (1)))
    ("C" ("Male" ("United-States") (12) ("<=50K") (0))
     ("Female" ("United-States") (5) ("<=50K") (0)))
    ("A" ("Female" ("United-States") (2) ("<=50K") (0))
     ("Male" ("United-States") (3) ("<=50K") (0))))
   ("A"
    ("D" ("Male" ("United-States") (7) ("<=50K") (0))
     ("Female" ("United-States") (2) ("<=50K") (0)))
    ("C" ("Male" ("United-States") (4) ("<=50K") (0))
     ("Female" ("United-States") (2) ("<=50K") (0)))
    ("A" ("Female" ("United-States") (4) ("<=50K") (0))
     ("Male" ("United-States") (1) ("<=50K") (0))))))
 ((14 13)
  (ROOT
   ("C" ("United-States" ("United-States") (40) ("<=50K") (0))
    ("South" ("South") (1) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Poland" ("Poland") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (28) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (21) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0))
    ("Honduras" ("Honduras") (1) ("<=50K") (0))
    ("Hong" ("Hong") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))))
 ((5 12)
  (ROOT
   ("A" ("D" ("Philippines") (1) ("<=50K") (21))
    ("B" ("United-States") (26) ("<=50K") (1))
    ("C" ("Philippines") (1) ("<=50K") (26))
    ("A" ("China") (1) ("<=50K") (18)))
   ("B" ("C" ("United-States") (1) ("<=50K") (0)))
   ("C" ("D" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("D" ("D" ("United-States") (1) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0)))))
 ((3 14)
  (ROOT
   ("United-States" ("D" ("United-States") (24) ("<=50K") (0))
    ("A" ("United-States") (16) ("<=50K") (0))
    ("C" ("United-States") (22) ("<=50K") (0))
    ("B" ("United-States") (28) ("<=50K") (0)))
   ("Philippines" ("B" ("Philippines") (1) ("<=50K") (0))
    ("D" ("Philippines") (2) ("<=50K") (0)))
   ("India" ("C" ("India") (1) ("<=50K") (0)))
   ("Canada" ("B" ("Canada") (1) ("<=50K") (0)))
   ("Portugal" ("A" ("Portugal") (1) ("<=50K") (0)))
   ("Germany" ("A" ("Germany") (1) ("<=50K") (0)))
   ("Vietnam" ("A" ("Vietnam") (1) ("<=50K") (0)))
   ("Guatemala" ("C" ("Guatemala") (1) ("<=50K") (0)))
   ("South" ("A" ("South") (1) ("<=50K") (0)))))
 ((14 12)
  (ROOT
   ("A" ("United-States" ("United-States") (89) ("<=50K") (0))
    ("Laos" ("Laos") (1) ("<=50K") (0)) ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("South" ("South") (1) ("<=50K") (0)) ("Haiti" ("Haiti") (1) ("<=50K") (0))
    ("China" ("China") (2) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (1) ("<=50K") (0)))))
 ((3 10 14)
  (ROOT
   ("United-States"
    ("Male" ("A" ("United-States") (19) ("<=50K") (0))
     ("B" ("United-States") (15) ("<=50K") (0))
     ("D" ("United-States") (16) ("<=50K") (0))
     ("C" ("United-States") (15) ("<=50K") (0)))
    ("Female" ("B" ("United-States") (8) ("<=50K") (0))
     ("A" ("United-States") (7) ("<=50K") (0))
     ("D" ("United-States") (7) ("<=50K") (0))
     ("C" ("United-States") (5) ("<=50K") (0))))
   ("Canada"
    ("Female" ("C" ("Canada") (1) ("<=50K") (0))
     ("A" ("Canada") (1) ("<=50K") (0))))
   ("Japan" ("Male" ("B" ("Japan") (1) ("<=50K") (0))))
   ("England" ("Male" ("A" ("England") (1) ("<=50K") (0))))
   ("Trinadad&Tobago" ("Female" ("C" ("Trinadad&Tobago") (1) ("<=50K") (0))))
   ("Mexico" ("Female" ("B" ("Mexico") (1) ("<=50K") (0)))
    ("Male" ("C" ("Mexico") (1) ("<=50K") (0))))
   ("Peru" ("Female" ("B" ("Peru") (1) ("<=50K") (0))))))
 ((9 2)
  (ROOT
   ("Local-gov" ("Asian-Pac-Islander" ("China") (1) ("<=50K") (0))
    ("White" ("United-States") (7) ("<=50K") (0))
    ("Black" ("United-States") (2) ("<=50K") (0)))
   ("Private" ("White" ("Canada") (2) ("<=50K") (55))
    ("Black" ("Jamaica") (2) ("<=50K") (5))
    ("Asian-Pac-Islander" ("Japan") (1) ("<=50K") (0))
    ("Amer-Indian-Eskimo" ("United-States") (1) ("<=50K") (0)))
   ("State-gov" ("White" ("United-States") (6) ("<=50K") (0)))
   ("Self-emp-not-inc" ("White" ("United-States") (10) ("<=50K") (0)))
   ("Self-emp-inc" ("White" ("United-States") (5) ("<=50K") (0)))
   ("Federal-gov" ("White" ("United-States") (2) ("<=50K") (0))
    ("Black" ("United-States") (1) ("<=50K") (0)))))
 ((14 12)
  (ROOT
   ("A" ("United-States" ("United-States") (86) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
    ("Peru" ("Peru") (1) ("<=50K") (0)) ("Iran" ("Iran") (1) ("<=50K") (0))
    ("Hong" ("Hong") (1) ("<=50K") (0)) ("Canada" ("Canada") (1) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (2) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (2) ("<=50K") (0)))))
 ((14 11)
  (ROOT ("B" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (84) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (3) ("<=50K") (0)) ("Iran" ("Iran") (1) ("<=50K") (0))
    ("Laos" ("Laos") (1) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (2) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Portugal" ("Portugal") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (2) ("<=50K") (0)))))
 ((10 14)
  (ROOT
   ("United-States" ("Male" ("United-States") (62) ("<=50K") (0))
    ("Female" ("United-States") (34) ("<=50K") (0)))
   ("Dominican-Republic" ("Female" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("Germany" ("Male" ("Germany") (1) ("<=50K") (0)))
   ("South" ("Male" ("South") (1) ("<=50K") (0)))
   ("Mexico" ("Male" ("Mexico") (1) ("<=50K") (0)))))
 ((14 13)
  (ROOT
   ("D" ("United-States" ("United-States") (22) ("<=50K") (0))
    ("Ireland" ("Ireland") (1) ("<=50K") (0))
    ("Nicaragua" ("Nicaragua") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (48) ("<=50K") (0))
    ("Mexico" ("Mexico") (3) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("A" ("Mexico" ("Mexico") (1) ("<=50K") (0))
    ("United-States" ("United-States") (20) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("China" ("China") (1) ("<=50K") (0)))))
 ((10 11)
  (ROOT ("C" ("Male" ("United-States") (1) ("<=50K") (0)))
   ("A" ("Male" ("Philippines") (3) ("<=50K") (47))
    ("Female" ("Ireland") (1) ("<=50K") (40)))
   ("D" ("Male" ("United-States") (7) ("<=50K") (0)))
   ("B" ("Male" ("United-States") (1) ("<=50K") (0)))))
 ((9 14)
  (ROOT
   ("United-States" ("Black" ("United-States") (15) ("<=50K") (0))
    ("White" ("United-States") (72) ("<=50K") (0))
    ("Asian-Pac-Islander" ("United-States") (1) ("<=50K") (0))
    ("Amer-Indian-Eskimo" ("United-States") (1) ("<=50K") (0)))
   ("El-Salvador" ("White" ("El-Salvador") (1) ("<=50K") (0)))
   ("Jamaica" ("Black" ("Jamaica") (2) ("<=50K") (0)))
   ("China" ("Asian-Pac-Islander" ("China") (2) ("<=50K") (0)))
   ("Dominican-Republic" ("White" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("Canada" ("White" ("Canada") (1) ("<=50K") (0)))
   ("Vietnam" ("Asian-Pac-Islander" ("Vietnam") (1) ("<=50K") (0)))
   ("Mexico" ("White" ("Mexico") (2) ("<=50K") (0)))
   ("England" ("White" ("England") (1) ("<=50K") (0)))))
 ((10 8)
  (ROOT
   ("Own-child" ("Female" ("United-States") (8) ("<=50K") (0))
    ("Male" ("United-States") (9) ("<=50K") (1)))
   ("Wife" ("Female" ("United-States") (6) ("<=50K") (0)))
   ("Not-in-family" ("Male" ("United-States") (9) ("<=50K") (2))
    ("Female" ("United-States") (9) ("<=50K") (0)))
   ("Husband" ("Male" ("United-States") (41) ("<=50K") (3)))
   ("Other-relative" ("Female" ("United-States") (3) ("<=50K") (0))
    ("Male" ("United-States") (1) ("<=50K") (0)))
   ("Unmarried" ("Male" ("United-States") (2) ("<=50K") (0))
    ("Female" ("United-States") (6) ("<=50K") (0)))))
 ((10 13)
  (ROOT
   ("D" ("Male" ("United-States") (22) ("<=50K") (2))
    ("Female" ("United-States") (4) ("<=50K") (1)))
   ("C" ("Female" ("United-States") (11) ("<=50K") (0))
    ("Male" ("Columbia") (1) ("<=50K") (28)))
   ("A" ("Female" ("United-States") (14) ("<=50K") (0))
    ("Male" ("Mexico") (1) ("<=50K") (16)))))
 ((12 11)
  (ROOT ("D" ("A" ("United-States") (5) ("<=50K") (1)))
   ("A" ("B" ("United-States") (2) ("<=50K") (1))
    ("A" ("Cuba") (2) ("<=50K") (84))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("B" ("A" ("United-States") (3) ("<=50K") (0)))
   ("C" ("A" ("United-States") (1) ("<=50K") (0)))))) )) 
(defvar results (quote 

(0.991415 0.9919 0.992 0.9902 0.9915 0.992 0.9917 0.9918 0.9901 0.992 0.9925
 0.9901 0.9913 0.9933 0.9918 0.9933 0.9909 0.9899 0.9903 0.9917 0.99) )) 
;;;;;;;;;;;;;

; Wich features are numeric? 0: not, 1: yes. *(not yet implemented)
(defvar *num-fetures* '(1 3 5 11 12 13))
; Total features *(not yet implemented)
(defvar *total-fetures* '14)
(defvar *min-fetures-sample* '2)
(defvar *max-fetures-sample* '5)
; Targets? 
(defvar *targets* '("<=50K" ">50K"))

; Model parameters.

; Number os trees in the forest:
(defvar *NTrees* 20)
; How much samples will be used to build the trees?
(defvar *NSamples* 100)
; To prune the worst trees with low rating accuracy.
; Prune below THPrec.
(defvar *THPrec* 0.99)

; Test rounds 
(defvar *TRounds* 20)
; Load the datasets to memory
(defvar *TSamples_train* 30000)
(defvar *TSamples_test* 10000)

; 16280 dataset.test.csv
; 32561 dataset.training.csv
; 48841 total
; Without samples with missing data:
; 15059 dataset.test.csv
; 30162 dataset.training.csv
; 45221 total

;EOF