(defvar forest-model (quote 

(((12 6)
  (ROOT ("Never-married" ("A" ("United-States") (30) ("<=50K") (5)))
   ("Married-civ-spouse" ("A" ("Nicaragua") (1) ("<=50K") (38))
    ("B" ("United-States") (2) ("<=50K") (0)))
   ("Divorced" ("A" ("United-States") (19) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("Widowed" ("A" ("United-States") (2) ("<=50K") (0)))
   ("Separated" ("A" ("United-States") (2) ("<=50K") (0)))))
 ((12 13)
  (ROOT ("D" ("A" ("Germany") (1) ("<=50K") (19)))
   ("C" ("A" ("United-States") (49) ("<=50K") (5))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("A" ("A" ("United-States") (23) ("<=50K") (2)))))
 ((13 14)
  (ROOT
   ("United-States" ("A" ("United-States") (19) ("<=50K") (0))
    ("D" ("United-States") (23) ("<=50K") (0))
    ("C" ("United-States") (48) ("<=50K") (0)))
   ("Guatemala" ("C" ("Guatemala") (1) ("<=50K") (0))
    ("A" ("Guatemala") (1) ("<=50K") (0)))
   ("Puerto-Rico" ("C" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("Mexico" ("C" ("Mexico") (1) ("<=50K") (0))
    ("D" ("Mexico") (1) ("<=50K") (0)))
   ("Nicaragua" ("C" ("Nicaragua") (1) ("<=50K") (0)))
   ("France" ("D" ("France") (1) ("<=50K") (0)))
   ("Trinadad&Tobago" ("C" ("Trinadad&Tobago") (1) ("<=50K") (0)))
   ("Jamaica" ("D" ("Jamaica") (1) ("<=50K") (0))
    ("C" ("Jamaica") (1) ("<=50K") (0)))))
 ((10 12)
  (ROOT
   ("A" ("Male" ("Portugal") (1) ("<=50K") (66))
    ("Female" ("Iran") (1) ("<=50K") (24)))
   ("B" ("Male" ("United-States") (1) ("<=50K") (0))
    ("Female" ("United-States") (2) ("<=50K") (0)))
   ("C" ("Male" ("United-States") (4) ("<=50K") (0))
    ("Female" ("United-States") (1) ("<=50K") (0)))))
 ((12 13 5)
  (ROOT
   ("B" ("D" ("A" ("United-States") (7) ("<=50K") (0)))
    ("C" ("A" ("United-States") (21) ("<=50K") (1)))
    ("A" ("A" ("United-States") (9) ("<=50K") (0))))
   ("A" ("C" ("A" ("Puerto-Rico") (1) ("<=50K") (6)))
    ("D" ("A" ("United-States") (3) ("<=50K") (1))
     ("B" ("United-States") (1) ("<=50K") (0)))
    ("A" ("A" ("United-States") (4) ("<=50K") (0))))
   ("C" ("D" ("A" ("United-States") (5) ("<=50K") (0)))
    ("A" ("A" ("United-States") (9) ("<=50K") (0)))
    ("C" ("A" ("United-States") (13) ("<=50K") (1))
     ("B" ("United-States") (1) ("<=50K") (0))))
   ("D"
    ("C" ("A" ("United-States") (6) ("<=50K") (1))
     ("C" ("Germany") (1) ("<=50K") (1)))
    ("A" ("A" ("United-States") (3) ("<=50K") (0)))
    ("D" ("A" ("United-States") (4) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0))))))
 ((13 14 11)
  (ROOT
   ("A"
    ("United-States" ("D" ("United-States") (31) ("<=50K") (0))
     ("A" ("United-States") (21) ("<=50K") (0))
     ("C" ("United-States") (25) ("<=50K") (0)))
    ("India" ("C" ("India") (1) ("<=50K") (0)))
    ("Mexico" ("A" ("Mexico") (1) ("<=50K") (0))
     ("C" ("Mexico") (2) ("<=50K") (0)))
    ("Poland" ("C" ("Poland") (1) ("<=50K") (0)))
    ("Scotland" ("C" ("Scotland") (1) ("<=50K") (0)))
    ("Portugal" ("C" ("Portugal") (1) ("<=50K") (0)))
    ("Cuba" ("C" ("Cuba") (1) ("<=50K") (0)))
    ("South" ("C" ("South") (1) ("<=50K") (0)))
    ("Canada" ("A" ("Canada") (1) ("<=50K") (0)))
    ("Hungary" ("D" ("Hungary") (1) ("<=50K") (0)))
    ("Puerto-Rico" ("A" ("Puerto-Rico") (1) ("<=50K") (0)))
    ("Philippines" ("D" ("Philippines") (1) ("<=50K") (0))))
   ("C"
    ("United-States" ("A" ("United-States") (1) ("<=50K") (0))
     ("C" ("United-States") (2) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0))))
   ("D"
    ("United-States" ("D" ("United-States") (1) ("<=50K") (0))
     ("A" ("United-States") (1) ("<=50K") (0))
     ("C" ("United-States") (1) ("<=50K") (0))))
   ("B"
    ("United-States" ("C" ("United-States") (1) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0))
     ("A" ("United-States") (1) ("<=50K") (0))))))
 ((10 13)
  (ROOT
   ("C" ("Male" ("Germany") (1) ("<=50K") (33))
    ("Female" ("Philippines") (1) ("<=50K") (19)))
   ("D" ("Male" ("United-States") (24) ("<=50K") (0))
    ("Female" ("United-States") (4) ("<=50K") (0)))
   ("A" ("Female" ("United-States") (8) ("<=50K") (2))
    ("Male" ("United-States") (7) ("<=50K") (1)))))
 ((5 14)
  (ROOT
   ("United-States" ("B" ("United-States") (33) ("<=50K") (0))
    ("A" ("United-States") (7) ("<=50K") (0))
    ("C" ("United-States") (33) ("<=50K") (0))
    ("D" ("United-States") (18) ("<=50K") (0)))
   ("Columbia" ("D" ("Columbia") (1) ("<=50K") (0)))
   ("Mexico" ("A" ("Mexico") (2) ("<=50K") (0)))
   ("Germany" ("C" ("Germany") (1) ("<=50K") (0))
    ("D" ("Germany") (1) ("<=50K") (0)))
   ("England" ("D" ("England") (1) ("<=50K") (0)))
   ("Peru" ("C" ("Peru") (1) ("<=50K") (0)))
   ("Taiwan" ("B" ("Taiwan") (1) ("<=50K") (0)))
   ("Philippines" ("A" ("Philippines") (1) ("<=50K") (0)))))
 ((1 14 3)
  (ROOT
   ("D"
    ("United-States" ("C" ("United-States") (4) ("<=50K") (0))
     ("A" ("United-States") (8) ("<=50K") (0))
     ("B" ("United-States") (6) ("<=50K") (0))
     ("D" ("United-States") (2) ("<=50K") (0)))
    ("India" ("B" ("India") (1) ("<=50K") (0)))
    ("Haiti" ("A" ("Haiti") (1) ("<=50K") (0)))
    ("Philippines" ("B" ("Philippines") (1) ("<=50K") (0))))
   ("C"
    ("United-States" ("C" ("United-States") (7) ("<=50K") (0))
     ("B" ("United-States") (5) ("<=50K") (0))
     ("D" ("United-States") (8) ("<=50K") (0))
     ("A" ("United-States") (4) ("<=50K") (0)))
    ("Cuba" ("D" ("Cuba") (1) ("<=50K") (0)))
    ("Germany" ("C" ("Germany") (1) ("<=50K") (0)))
    ("Italy" ("C" ("Italy") (1) ("<=50K") (0))))
   ("B"
    ("United-States" ("C" ("United-States") (9) ("<=50K") (0))
     ("D" ("United-States") (8) ("<=50K") (0))
     ("A" ("United-States") (5) ("<=50K") (0))
     ("B" ("United-States") (3) ("<=50K") (0)))
    ("Laos" ("A" ("Laos") (1) ("<=50K") (0)))
    ("Trinadad&Tobago" ("D" ("Trinadad&Tobago") (1) ("<=50K") (0)))
    ("Japan" ("B" ("Japan") (1) ("<=50K") (0))))
   ("A"
    ("United-States" ("D" ("United-States") (5) ("<=50K") (0))
     ("C" ("United-States") (6) ("<=50K") (0))
     ("B" ("United-States") (2) ("<=50K") (0))
     ("A" ("United-States") (7) ("<=50K") (0)))
    ("Japan" ("C" ("Japan") (1) ("<=50K") (0)))
    ("England" ("C" ("England") (1) ("<=50K") (0))))))
 ((12 11)
  (ROOT
   ("A" ("A" ("India") (2) ("<=50K") (89))
    ("B" ("United-States") (4) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("D" ("A" ("United-States") (1) ("<=50K") (0)))
   ("B" ("A" ("United-States") (1) ("<=50K") (0)))
   ("C" ("A" ("United-States") (2) ("<=50K") (0)))))
 ((11 12)
  (ROOT
   ("A" ("A" ("Vietnam") (1) ("<=50K") (85))
    ("B" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (3) ("<=50K") (0))
    ("D" ("United-States") (4) ("<=50K") (0)))
   ("B" ("A" ("United-States") (2) ("<=50K") (0)))
   ("C" ("A" ("United-States") (4) ("<=50K") (0)))))
 ((14 11 12)
  (ROOT ("C" ("A" ("United-States" ("United-States") (2) ("<=50K") (0))))
   ("A"
    ("A" ("United-States" ("United-States") (79) ("<=50K") (0))
     ("Jamaica" ("Jamaica") (1) ("<=50K") (0))
     ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0))
     ("Greece" ("Greece") (1) ("<=50K") (0))
     ("Yugoslavia" ("Yugoslavia") (1) ("<=50K") (0))
     ("England" ("England") (1) ("<=50K") (0))
     ("Mexico" ("Mexico") (3) ("<=50K") (0))
     ("Nicaragua" ("Nicaragua") (1) ("<=50K") (0))
     ("Italy" ("Italy") (1) ("<=50K") (0)))
    ("C" ("United-States" ("United-States") (2) ("<=50K") (0)))
    ("D" ("United-States" ("United-States") (4) ("<=50K") (0)))
    ("B" ("United-States" ("United-States") (1) ("<=50K") (0))))
   ("B" ("A" ("United-States" ("United-States") (2) ("<=50K") (0))))))
 ((14 9)
  (ROOT
   ("Asian-Pac-Islander" ("South" ("South") (2) ("<=50K") (0))
    ("Thailand" ("Thailand") (1) ("<=50K") (0))
    ("Taiwan" ("Taiwan") (1) ("<=50K") (0)))
   ("White" ("United-States" ("United-States") (80) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (4) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0)))
   ("Black" ("United-States" ("United-States") (9) ("<=50K") (0)))))
 ((10 2)
  (ROOT
   ("Private" ("Male" ("Italy") (1) ("<=50K") (45))
    ("Female" ("Dominican-Republic") (1) ("<=50K") (22)))
   ("Self-emp-not-inc" ("Male" ("United-States") (9) ("<=50K") (2))
    ("Female" ("United-States") (4) ("<=50K") (0)))
   ("State-gov" ("Male" ("United-States") (2) ("<=50K") (0))
    ("Female" ("United-States") (5) ("<=50K") (0)))
   ("Local-gov" ("Female" ("United-States") (1) ("<=50K") (0))
    ("Male" ("United-States") (2) ("<=50K") (0)))
   ("Federal-gov" ("Female" ("United-States") (1) ("<=50K") (0))
    ("Male" ("United-States") (2) ("<=50K") (0)))
   ("Self-emp-inc" ("Male" ("United-States") (2) ("<=50K") (0))
    ("Female" ("United-States") (1) ("<=50K") (0)))))
 ((12 2)
  (ROOT
   ("Private" ("A" ("Haiti") (1) ("<=50K") (73))
    ("D" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("Self-emp-not-inc" ("A" ("United-States") (11) ("<=50K") (0)))
   ("Federal-gov" ("A" ("United-States") (3) ("<=50K") (0)))
   ("Local-gov" ("C" ("United-States") (1) ("<=50K") (0))
    ("A" ("United-States") (4) ("<=50K") (1)))
   ("Without-pay" ("A" ("United-States") (1) ("<=50K") (0)))
   ("State-gov" ("A" ("United-States") (2) ("<=50K") (0)))
   ("Self-emp-inc" ("A" ("United-States") (1) ("<=50K") (0)))))
 ((3 14)
  (ROOT
   ("United-States" ("A" ("United-States") (29) ("<=50K") (0))
    ("D" ("United-States") (21) ("<=50K") (0))
    ("B" ("United-States") (16) ("<=50K") (0))
    ("C" ("United-States") (25) ("<=50K") (0)))
   ("Haiti" ("C" ("Haiti") (1) ("<=50K") (0)))
   ("Germany" ("D" ("Germany") (1) ("<=50K") (0)))
   ("Iran" ("B" ("Iran") (1) ("<=50K") (0)))
   ("South" ("C" ("South") (1) ("<=50K") (0)))
   ("Columbia" ("D" ("Columbia") (1) ("<=50K") (0)))
   ("Mexico" ("D" ("Mexico") (1) ("<=50K") (0)))
   ("El-Salvador" ("C" ("El-Salvador") (1) ("<=50K") (0)))
   ("India" ("A" ("India") (1) ("<=50K") (0)))
   ("Guatemala" ("B" ("Guatemala") (1) ("<=50K") (0)))))
 ((14 9)
  (ROOT
   ("White" ("United-States" ("United-States") (77) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (1) ("<=50K") (0))
    ("Nicaragua" ("Nicaragua") (1) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Poland" ("Poland") (1) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("Asian-Pac-Islander" ("Philippines" ("Philippines") (2) ("<=50K") (0))
    ("China" ("China") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0)))
   ("Black" ("United-States" ("United-States") (8) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (1) ("<=50K") (0)))
   ("Amer-Indian-Eskimo"
    ("United-States" ("United-States") (2) ("<=50K") (0)))))
 ((13 14)
  (ROOT
   ("United-States" ("C" ("United-States") (36) ("<=50K") (0))
    ("D" ("United-States") (44) ("<=50K") (0))
    ("A" ("United-States") (12) ("<=50K") (0)))
   ("China" ("C" ("China") (1) ("<=50K") (0)))
   ("Puerto-Rico" ("C" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("Mexico" ("C" ("Mexico") (2) ("<=50K") (0))
    ("D" ("Mexico") (1) ("<=50K") (0)) ("A" ("Mexico") (1) ("<=50K") (0)))
   ("Haiti" ("D" ("Haiti") (1) ("<=50K") (0)))
   ("Jamaica" ("A" ("Jamaica") (1) ("<=50K") (0)))))
 ((5 3)
  (ROOT
   ("D" ("D" ("United-States") (7) ("<=50K") (0))
    ("A" ("United-States") (5) ("<=50K") (1))
    ("C" ("United-States") (4) ("<=50K") (0))
    ("B" ("United-States") (4) ("<=50K") (0)))
   ("C" ("C" ("United-States") (8) ("<=50K") (0))
    ("B" ("United-States") (5) ("<=50K") (1))
    ("D" ("United-States") (5) ("<=50K") (0))
    ("A" ("United-States") (3) ("<=50K") (1)))
   ("A" ("C" ("United-States") (8) ("<=50K") (0))
    ("B" ("United-States") (9) ("<=50K") (0))
    ("D" ("United-States") (5) ("<=50K") (0))
    ("A" ("United-States") (4) ("<=50K") (0)))
   ("B" ("B" ("United-States") (11) ("<=50K") (0))
    ("D" ("United-States") (8) ("<=50K") (0))
    ("C" ("United-States") (6) ("<=50K") (0))
    ("A" ("United-States") (5) ("<=50K") (0)))))
 ((12 11)
  (ROOT
   ("A" ("A" ("Puerto-Rico") (1) ("<=50K") (86))
    ("C" ("United-States") (4) ("<=50K") (0))
    ("B" ("United-States") (2) ("<=50K") (0))
    ("D" ("United-States") (1) ("<=50K") (0)))
   ("C" ("A" ("United-States") (2) ("<=50K") (1)))
   ("D" ("A" ("United-States") (2) ("<=50K") (0)))
   ("B" ("A" ("United-States") (1) ("<=50K") (0)))))) )) 
(defvar results (quote 

(0.9987 0.9985 0.9991 0.9989 0.9985 0.9991 0.9993 0.9989 0.9984 0.9988 0.999
 0.9981 0.9984 0.9988 0.9987 0.9987 0.9977 0.9986 0.9988 0.9989 0.9988) )) 
;;;;;;;;;;;;;

; Wich features are numeric? 0: not, 1: yes. *(not yet implemented)
(defvar *num-fetures* '(1 3 5 11 12 13))
; Total features *(not yet implemented)
(defvar *total-fetures* '14)
(defvar *min-fetures-sample* '2)
(defvar *max-fetures-sample* '5)
; Targets? 
(defvar *targets* '("<=50K" ">50K"))

; Model parameters.

; Number os trees in the forest:
(defvar *NTrees* 20)
; How much samples will be used to build the trees?
(defvar *NSamples* 100)
; To prune the worst trees with low rating accuracy.
; Prune below THPrec.
(defvar *THPrec* 0.99)

; Test rounds 
(defvar *TRounds* 20)
; Load the datasets to memory
(defvar *TSamples_train* 30000)
(defvar *TSamples_test* 10000)

; 16280 dataset.test.csv
; 32561 dataset.training.csv
; 48841 total
; Without samples with missing data:
; 15059 dataset.test.csv
; 30162 dataset.training.csv
; 45221 total

;EOF