(defvar forest-model (quote 

(((13 8 14)
  (ROOT
   ("United-States"
    ("Not-in-family" ("A" ("United-States") (6) ("<=50K") (0))
     ("C" ("United-States") (13) ("<=50K") (0))
     ("D" ("United-States") (6) ("<=50K") (0)))
    ("Own-child" ("A" ("United-States") (8) ("<=50K") (0))
     ("C" ("United-States") (6) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0)))
    ("Unmarried" ("C" ("United-States") (4) ("<=50K") (0))
     ("A" ("United-States") (4) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0)))
    ("Husband" ("A" ("United-States") (4) ("<=50K") (0))
     ("D" ("United-States") (11) ("<=50K") (0))
     ("C" ("United-States") (19) ("<=50K") (0)))
    ("Wife" ("A" ("United-States") (2) ("<=50K") (0))
     ("C" ("United-States") (1) ("<=50K") (0))
     ("D" ("United-States") (1) ("<=50K") (0)))
    ("Other-relative" ("A" ("United-States") (1) ("<=50K") (0))))
   ("Peru" ("Not-in-family" ("A" ("Peru") (1) ("<=50K") (0))))
   ("Philippines" ("Other-relative" ("C" ("Philippines") (1) ("<=50K") (0))))
   ("Canada" ("Not-in-family" ("A" ("Canada") (1) ("<=50K") (0))))
   ("Puerto-Rico" ("Unmarried" ("D" ("Puerto-Rico") (1) ("<=50K") (0))))
   ("Columbia" ("Wife" ("C" ("Columbia") (1) ("<=50K") (0)))
    ("Own-child" ("A" ("Columbia") (1) ("<=50K") (0))))
   ("El-Salvador" ("Not-in-family" ("A" ("El-Salvador") (1) ("<=50K") (0))))
   ("Cuba" ("Husband" ("C" ("Cuba") (2) ("<=50K") (0))))
   ("Guatemala" ("Not-in-family" ("A" ("Guatemala") (1) ("<=50K") (0))))
   ("Ecuador" ("Not-in-family" ("C" ("Ecuador") (1) ("<=50K") (0))))
   ("Japan" ("Husband" ("C" ("Japan") (1) ("<=50K") (0))))))
 ((12 14)
  (ROOT
   ("United-States" ("A" ("United-States") (89) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("Mexico" ("A" ("Mexico") (2) ("<=50K") (0)))
   ("South" ("A" ("South") (1) ("<=50K") (0)))
   ("Guatemala" ("A" ("Guatemala") (2) ("<=50K") (0)))
   ("England" ("A" ("England") (1) ("<=50K") (0)))
   ("Greece" ("A" ("Greece") (1) ("<=50K") (0)))
   ("Cuba" ("A" ("Cuba") (1) ("<=50K") (0)))
   ("Honduras" ("A" ("Honduras") (1) ("<=50K") (0)))
   ("Outlying-US(Guam-USVI-etc)"
    ("A" ("Outlying-US(Guam-USVI-etc)") (1) ("<=50K") (0)))))
 ((3 10)
  (ROOT
   ("Male" ("D" ("United-States") (13) ("<=50K") (3))
    ("A" ("United-States") (23) ("<=50K") (1))
    ("C" ("United-States") (16) ("<=50K") (0))
    ("B" ("United-States") (10) ("<=50K") (0)))
   ("Female" ("D" ("United-States") (3) ("<=50K") (2))
    ("A" ("United-States") (8) ("<=50K") (0))
    ("C" ("United-States") (10) ("<=50K") (0))
    ("B" ("United-States") (11) ("<=50K") (0)))))
 ((14 13)
  (ROOT
   ("C" ("United-States" ("United-States") (48) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (24) ("<=50K") (0))
    ("Peru" ("Peru") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (22) ("<=50K") (0))
    ("Japan" ("Japan") (1) ("<=50K") (0)))))
 ((3 13)
  (ROOT
   ("D" ("C" ("United-States") (12) ("<=50K") (2))
    ("D" ("United-States") (9) ("<=50K") (0))
    ("B" ("United-States") (8) ("<=50K") (1))
    ("A" ("Greece") (1) ("<=50K") (7)))
   ("C" ("A" ("United-States") (6) ("<=50K") (0))
    ("B" ("United-States") (12) ("<=50K") (0))
    ("D" ("China") (1) ("<=50K") (10))
    ("C" ("United-States") (9) ("<=50K") (1)))
   ("A" ("C" ("United-States") (9) ("<=50K") (0))
    ("D" ("United-States") (4) ("<=50K") (3))
    ("B" ("United-States") (4) ("<=50K") (0))
    ("A" ("United-States") (1) ("<=50K") (0)))))
 ((2 11)
  (ROOT
   ("A" ("Private" ("Puerto-Rico") (2) ("<=50K") (65))
    ("Federal-gov" ("United-States") (6) ("<=50K") (0))
    ("Local-gov" ("United-States") (9) ("<=50K") (0))
    ("State-gov" ("United-States") (2) ("<=50K") (0))
    ("Self-emp-not-inc" ("United-States") (4) ("<=50K") (0))
    ("Self-emp-inc" ("United-States") (1) ("<=50K") (0))
    ("Without-pay" ("United-States") (1) ("<=50K") (0)))
   ("D" ("Private" ("United-States") (4) ("<=50K") (0))
    ("Self-emp-not-inc" ("United-States") (1) ("<=50K") (0)))
   ("C" ("Local-gov" ("United-States") (1) ("<=50K") (0))
    ("Private" ("United-States") (1) ("<=50K") (0)))
   ("B" ("Private" ("United-States") (2) ("<=50K") (0))
    ("Self-emp-not-inc" ("Italy") (1) ("<=50K") (0)))))
 ((12 3)
  (ROOT
   ("A" ("A" ("United-States") (34) ("<=50K") (5))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("D" ("A" ("Mexico") (1) ("<=50K") (19))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("C" ("A" ("United-States") (19) ("<=50K") (2)))
   ("B" ("A" ("United-States") (17) ("<=50K") (1)))))
 ((14 11)
  (ROOT
   ("A" ("United-States" ("United-States") (79) ("<=50K") (0))
    ("Germany" ("Germany") (2) ("<=50K") (0))
    ("China" ("China") (1) ("<=50K") (0)) ("Japan" ("Japan") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (5) ("<=50K") (0)) ("Peru" ("Peru") (1) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0))
    ("Iran" ("Iran") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (4) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (1) ("<=50K") (0)))))
 ((9 14)
  (ROOT
   ("United-States" ("White" ("United-States") (78) ("<=50K") (0))
    ("Black" ("United-States") (8) ("<=50K") (0))
    ("Asian-Pac-Islander" ("United-States") (1) ("<=50K") (0))
    ("Amer-Indian-Eskimo" ("United-States") (2) ("<=50K") (0)))
   ("Nicaragua" ("White" ("Nicaragua") (1) ("<=50K") (0)))
   ("Thailand" ("Asian-Pac-Islander" ("Thailand") (1) ("<=50K") (0)))
   ("Canada" ("White" ("Canada") (1) ("<=50K") (0)))
   ("Guatemala" ("White" ("Guatemala") (1) ("<=50K") (0)))
   ("Mexico" ("White" ("Mexico") (3) ("<=50K") (0)))
   ("Portugal" ("White" ("Portugal") (1) ("<=50K") (0)))
   ("England" ("White" ("England") (1) ("<=50K") (0)))
   ("Puerto-Rico" ("White" ("Puerto-Rico") (1) ("<=50K") (0)))
   ("Vietnam" ("Asian-Pac-Islander" ("Vietnam") (1) ("<=50K") (0)))))
 ((9 14 1)
  (ROOT
   ("B" ("Nicaragua" ("White" ("Nicaragua") (1) ("<=50K") (0)))
    ("United-States" ("White" ("United-States") (15) ("<=50K") (0))
     ("Black" ("United-States") (3) ("<=50K") (0))
     ("Asian-Pac-Islander" ("United-States") (2) ("<=50K") (0))
     ("Amer-Indian-Eskimo" ("United-States") (3) ("<=50K") (0)))
    ("Mexico" ("White" ("Mexico") (1) ("<=50K") (0)))
    ("Dominican-Republic" ("White" ("Dominican-Republic") (1) ("<=50K") (0)))
    ("Yugoslavia" ("White" ("Yugoslavia") (1) ("<=50K") (0)))
    ("Japan" ("White" ("Japan") (1) ("<=50K") (0))))
   ("D" ("Laos" ("Asian-Pac-Islander" ("Laos") (1) ("<=50K") (0)))
    ("United-States" ("White" ("United-States") (22) ("<=50K") (0))
     ("Black" ("United-States") (4) ("<=50K") (0)))
    ("Mexico" ("White" ("Mexico") (1) ("<=50K") (0)))
    ("England" ("White" ("England") (1) ("<=50K") (0)))
    ("El-Salvador" ("White" ("El-Salvador") (1) ("<=50K") (0)))
    ("Italy" ("White" ("Italy") (1) ("<=50K") (0))))
   ("A"
    ("United-States" ("White" ("United-States") (16) ("<=50K") (0))
     ("Black" ("United-States") (1) ("<=50K") (0)))
    ("El-Salvador" ("White" ("El-Salvador") (1) ("<=50K") (0))))
   ("C"
    ("United-States" ("White" ("United-States") (20) ("<=50K") (0))
     ("Black" ("United-States") (1) ("<=50K") (0)))
    ("Haiti" ("Black" ("Haiti") (1) ("<=50K") (0)))
    ("Cuba" ("White" ("Cuba") (1) ("<=50K") (0))))))
 ((1 6)
  (ROOT
   ("Never-married" ("A" ("United-States") (15) ("<=50K") (3))
    ("B" ("United-States") (9) ("<=50K") (3))
    ("D" ("United-States") (2) ("<=50K") (0))
    ("C" ("United-States") (3) ("<=50K") (0)))
   ("Married-civ-spouse" ("B" ("United-States") (9) ("<=50K") (2))
    ("D" ("United-States") (11) ("<=50K") (3))
    ("A" ("United-States") (3) ("<=50K") (1))
    ("C" ("Trinadad&Tobago") (1) ("<=50K") (10)))
   ("Divorced" ("D" ("United-States") (6) ("<=50K") (0))
    ("C" ("United-States") (7) ("<=50K") (0))
    ("B" ("United-States") (2) ("<=50K") (0))
    ("A" ("United-States") (2) ("<=50K") (0)))
   ("Separated" ("A" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0))
    ("D" ("United-States") (1) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0)))
   ("Widowed" ("D" ("Mexico") (1) ("<=50K") (2)))
   ("Married-spouse-absent" ("B" ("United-States") (1) ("<=50K") (0)))))
 ((4 14)
  (ROOT
   ("United-States" ("Masters" ("United-States") (5) ("<=50K") (0))
    ("Bachelors" ("United-States") (13) ("<=50K") (0))
    ("Assoc-acdm" ("United-States") (4) ("<=50K") (0))
    ("Some-college" ("United-States") (16) ("<=50K") (0))
    ("HS-grad" ("United-States") (33) ("<=50K") (0))
    ("12th" ("United-States") (2) ("<=50K") (0))
    ("7th-8th" ("United-States") (3) ("<=50K") (0))
    ("11th" ("United-States") (4) ("<=50K") (0))
    ("Doctorate" ("United-States") (1) ("<=50K") (0))
    ("Prof-school" ("United-States") (4) ("<=50K") (0))
    ("10th" ("United-States") (4) ("<=50K") (0))
    ("Assoc-voc" ("United-States") (3) ("<=50K") (0))
    ("9th" ("United-States") (1) ("<=50K") (0)))
   ("Mexico" ("5th-6th" ("Mexico") (1) ("<=50K") (0))
    ("Some-college" ("Mexico") (1) ("<=50K") (0)))
   ("China" ("Masters" ("China") (1) ("<=50K") (0)))
   ("Iran" ("Doctorate" ("Iran") (1) ("<=50K") (0)))
   ("Thailand" ("HS-grad" ("Thailand") (1) ("<=50K") (0)))
   ("Philippines" ("Some-college" ("Philippines") (1) ("<=50K") (0)))
   ("India" ("Masters" ("India") (1) ("<=50K") (0)))))
 ((14 5)
  (ROOT
   ("C" ("United-States" ("United-States") (22) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0))
    ("South" ("South") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (28) ("<=50K") (0))
    ("Poland" ("Poland") (1) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (8) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (30) ("<=50K") (0))
    ("France" ("France") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0))
    ("England" ("England") (2) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0)))))
 ((1 12)
  (ROOT
   ("A" ("A" ("United-States") (22) ("<=50K") (7))
    ("B" ("United-States") (17) ("<=50K") (0))
    ("D" ("France") (2) ("<=50K") (23))
    ("C" ("United-States") (21) ("<=50K") (2)))
   ("C" ("B" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0))
    ("D" ("United-States") (2) ("<=50K") (0))
    ("A" ("United-States") (1) ("<=50K") (0)))
   ("B" ("D" ("India") (1) ("<=50K") (0)))))
 ((2 12)
  (ROOT
   ("A" ("Private" ("Puerto-Rico") (1) ("<=50K") (69))
    ("Local-gov" ("United-States") (10) ("<=50K") (0))
    ("Self-emp-inc" ("United-States") (4) ("<=50K") (0))
    ("Federal-gov" ("United-States") (3) ("<=50K") (0))
    ("State-gov" ("United-States") (3) ("<=50K") (0))
    ("Self-emp-not-inc" ("United-States") (5) ("<=50K") (1)))
   ("C" ("Self-emp-inc" ("United-States") (1) ("<=50K") (0))
    ("Local-gov" ("United-States") (1) ("<=50K") (0))
    ("Private" ("United-States") (1) ("<=50K") (0)))
   ("B" ("Local-gov" ("United-States") (1) ("<=50K") (0)))))
 ((1 11)
  (ROOT
   ("A" ("D" ("United-States") (23) ("<=50K") (0))
    ("B" ("United-States") (17) ("<=50K") (3))
    ("A" ("Mexico") (2) ("<=50K") (25))
    ("C" ("United-States") (20) ("<=50K") (1)))
   ("D" ("D" ("Japan") (1) ("<=50K") (1))
    ("B" ("United-States") (3) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("C" ("A" ("United-States") (1) ("<=50K") (0)))
   ("B" ("C" ("United-States") (1) ("<=50K") (0))
    ("B" ("Philippines") (1) ("<=50K") (0)))))
 ((14 13)
  (ROOT
   ("D" ("United-States" ("United-States") (29) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0)))
   ("C" ("Canada" ("Canada") (2) ("<=50K") (0))
    ("United-States" ("United-States") (43) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (1) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0))
    ("Vietnam" ("Vietnam") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (15) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)) ("Cuba" ("Cuba") (1) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0)))))
 ((6 10)
  (ROOT
   ("Male" ("Never-married" ("United-States") (17) ("<=50K") (0))
    ("Divorced" ("United-States") (3) ("<=50K") (0))
    ("Married-civ-spouse" ("United-States") (38) ("<=50K") (2))
    ("Separated" ("United-States") (1) ("<=50K") (0)))
   ("Female" ("Never-married" ("United-States") (13) ("<=50K") (2))
    ("Married-civ-spouse" ("United-States") (4) ("<=50K") (1))
    ("Separated" ("United-States") (6) ("<=50K") (0))
    ("Divorced" ("United-States") (9) ("<=50K") (0))
    ("Married-spouse-absent" ("United-States") (1) ("<=50K") (0))
    ("Widowed" ("United-States") (2) ("<=50K") (0))
    ("Married-AF-spouse" ("United-States") (1) ("<=50K") (0)))))
 ((8 5)
  (ROOT
   ("C" ("Own-child" ("United-States") (6) ("<=50K") (0))
    ("Husband" ("United-States") (10) ("<=50K") (0))
    ("Not-in-family" ("United-States") (8) ("<=50K") (0))
    ("Unmarried" ("Jamaica") (1) ("<=50K") (2))
    ("Wife" ("United-States") (1) ("<=50K") (0))
    ("Other-relative" ("United-States") (1) ("<=50K") (0)))
   ("D" ("Not-in-family" ("United-States") (9) ("<=50K") (0))
    ("Husband" ("England") (1) ("<=50K") (11))
    ("Own-child" ("United-States") (2) ("<=50K") (0))
    ("Unmarried" ("United-States") (3) ("<=50K") (1)))
   ("A" ("Unmarried" ("United-States") (2) ("<=50K") (0))
    ("Other-relative" ("Cuba") (1) ("<=50K") (2))
    ("Husband" ("United-States") (3) ("<=50K") (0))
    ("Not-in-family" ("United-States") (3) ("<=50K") (0))
    ("Wife" ("United-States") (1) ("<=50K") (1))
    ("Own-child" ("United-States") (1) ("<=50K") (1)))
   ("B" ("Not-in-family" ("United-States") (6) ("<=50K") (1))
    ("Own-child" ("United-States") (2) ("<=50K") (0))
    ("Husband" ("United-States") (11) ("<=50K") (2))
    ("Unmarried" ("United-States") (5) ("<=50K") (0))
    ("Wife" ("United-States") (2) ("<=50K") (0)))))
 ((14 3)
  (ROOT
   ("A" ("United-States" ("United-States") (22) ("<=50K") (0))
    ("Portugal" ("Portugal") (1) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (27) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (24) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("England" ("England") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (16) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Japan" ("Japan") (1) ("<=50K") (0)))))) )) 
(defvar results (quote 

(0.97653997 0.9791 0.9752 0.9776 0.9758 0.9752 0.9759 0.9782 0.9795 0.9765
 0.9797 0.9757 0.9759 0.9755 0.9743 0.9768 0.9747 0.9737 0.9791 0.9777 0.9747) )) 
;;;;;;;;;;;;;

; Wich features are numeric? 0: not, 1: yes. *(not yet implemented)
(defvar *num-fetures* '(1 3 5 11 12 13))
; Total features *(not yet implemented)
(defvar *total-fetures* '14)
(defvar *min-fetures-sample* '2)
(defvar *max-fetures-sample* '5)
; Targets? 
(defvar *targets* '("<=50K" ">50K"))

; Model parameters.

; Number os trees in the forest:
(defvar *NTrees* 20)
; How much samples will be used to build the trees?
(defvar *NSamples* 100)
; To prune the worst trees with low rating accuracy.
; Prune below THPrec.
(defvar *THPrec* 0.97)

; Test rounds 
(defvar *TRounds* 20)
; Load the datasets to memory
(defvar *TSamples_train* 30000)
(defvar *TSamples_test* 10000)

; 16280 dataset.test.csv
; 32561 dataset.training.csv
; 48841 total
; Without samples with missing data:
; 15059 dataset.test.csv
; 30162 dataset.training.csv
; 45221 total

;EOF