(defvar forest-model (quote 

(((12 2)
  (ROOT ("Self-emp-not-inc" ("A" ("United-States") (11) ("<=50K") (0)))
   ("Local-gov" ("A" ("United-States") (8) ("<=50K") (0)))
   ("Private" ("A" ("England") (1) ("<=50K") (69))
    ("B" ("United-States") (2) ("<=50K") (0))
    ("C" ("United-States") (2) ("<=50K") (0)))
   ("Federal-gov" ("A" ("United-States") (5) ("<=50K") (0)))
   ("Self-emp-inc" ("A" ("United-States") (1) ("<=50K") (0)))
   ("State-gov" ("A" ("United-States") (1) ("<=50K") (0)))))
 ((14 10 13)
  (ROOT
   ("C"
    ("Female" ("United-States" ("United-States") (14) ("<=50K") (0))
     ("Jamaica" ("Jamaica") (1) ("<=50K") (0)))
    ("Male" ("United-States" ("United-States") (31) ("<=50K") (0))
     ("Mexico" ("Mexico") (2) ("<=50K") (0))
     ("India" ("India") (1) ("<=50K") (0))
     ("Vietnam" ("Vietnam") (1) ("<=50K") (0))
     ("Columbia" ("Columbia") (1) ("<=50K") (0))))
   ("D" ("Female" ("United-States" ("United-States") (4) ("<=50K") (0)))
    ("Male" ("United-States" ("United-States") (22) ("<=50K") (0))
     ("Germany" ("Germany") (1) ("<=50K") (0))))
   ("A" ("Male" ("United-States" ("United-States") (10) ("<=50K") (0)))
    ("Female" ("United-States" ("United-States") (10) ("<=50K") (0))
     ("Nicaragua" ("Nicaragua") (1) ("<=50K") (0))
     ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0))))))
 ((12 10)
  (ROOT
   ("Female" ("A" ("United-States") (30) ("<=50K") (6))
    ("B" ("United-States") (1) ("<=50K") (0))
    ("C" ("United-States") (1) ("<=50K") (0)))
   ("Male" ("A" ("Greece") (1) ("<=50K") (54))
    ("C" ("United-States") (5) ("<=50K") (0))
    ("B" ("United-States") (1) ("<=50K") (0))
    ("D" ("United-States") (1) ("<=50K") (0)))))
 ((6 14)
  (ROOT
   ("United-States" ("Never-married" ("United-States") (28) ("<=50K") (0))
    ("Divorced" ("United-States") (11) ("<=50K") (0))
    ("Married-civ-spouse" ("United-States") (44) ("<=50K") (0))
    ("Separated" ("United-States") (5) ("<=50K") (0))
    ("Widowed" ("United-States") (2) ("<=50K") (0))
    ("Married-spouse-absent" ("United-States") (1) ("<=50K") (0)))
   ("Philippines" ("Never-married" ("Philippines") (1) ("<=50K") (0)))
   ("Germany" ("Married-civ-spouse" ("Germany") (2) ("<=50K") (0)))
   ("Japan" ("Never-married" ("Japan") (1) ("<=50K") (0)))
   ("Jamaica" ("Never-married" ("Jamaica") (1) ("<=50K") (0)))
   ("Iran" ("Married-civ-spouse" ("Iran") (1) ("<=50K") (0)))
   ("Cuba" ("Married-civ-spouse" ("Cuba") (1) ("<=50K") (0)))
   ("Mexico" ("Married-civ-spouse" ("Mexico") (1) ("<=50K") (0))
    ("Never-married" ("Mexico") (1) ("<=50K") (0)))))
 ((9 12 14)
  (ROOT
   ("United-States"
    ("A" ("White" ("United-States") (74) ("<=50K") (0))
     ("Black" ("United-States") (11) ("<=50K") (0))
     ("Amer-Indian-Eskimo" ("United-States") (1) ("<=50K") (0)))
    ("C" ("White" ("United-States") (3) ("<=50K") (0)))
    ("D" ("White" ("United-States") (1) ("<=50K") (0))))
   ("Columbia" ("A" ("White" ("Columbia") (2) ("<=50K") (0))))
   ("Italy" ("A" ("White" ("Italy") (1) ("<=50K") (0))))
   ("Jamaica"
    ("A" ("Black" ("Jamaica") (1) ("<=50K") (0))
     ("White" ("Jamaica") (1) ("<=50K") (0))))
   ("Mexico" ("A" ("White" ("Mexico") (1) ("<=50K") (0))))
   ("Haiti" ("A" ("Black" ("Haiti") (1) ("<=50K") (0))))
   ("South" ("A" ("Asian-Pac-Islander" ("South") (1) ("<=50K") (0))))
   ("Guatemala" ("A" ("White" ("Guatemala") (1) ("<=50K") (0))))
   ("Philippines" ("A" ("White" ("Philippines") (1) ("<=50K") (0))))))
 ((11 14 12)
  (ROOT
   ("A" ("El-Salvador" ("A" ("El-Salvador") (2) ("<=50K") (0)))
    ("United-States" ("A" ("United-States") (77) ("<=50K") (0))
     ("B" ("United-States") (1) ("<=50K") (0))
     ("C" ("United-States") (3) ("<=50K") (0))
     ("D" ("United-States") (2) ("<=50K") (0)))
    ("Mexico" ("A" ("Mexico") (4) ("<=50K") (0)))
    ("Philippines" ("A" ("Philippines") (1) ("<=50K") (0)))
    ("China" ("A" ("China") (1) ("<=50K") (0)))
    ("Jamaica" ("A" ("Jamaica") (1) ("<=50K") (0)))
    ("Germany" ("A" ("Germany") (1) ("<=50K") (0)))
    ("Taiwan" ("A" ("Taiwan") (1) ("<=50K") (0)))
    ("Guatemala" ("A" ("Guatemala") (1) ("<=50K") (0)))
    ("Cuba" ("A" ("Cuba") (1) ("<=50K") (0)))
    ("Japan" ("D" ("Japan") (1) ("<=50K") (0))))
   ("C" ("China" ("A" ("China") (1) ("<=50K") (0)))
    ("United-States" ("A" ("United-States") (1) ("<=50K") (0))))
   ("B" ("Vietnam" ("A" ("Vietnam") (1) ("<=50K") (0))))))
 ((6 14)
  (ROOT
   ("United-States" ("Divorced" ("United-States") (13) ("<=50K") (0))
    ("Married-civ-spouse" ("United-States") (46) ("<=50K") (0))
    ("Never-married" ("United-States") (27) ("<=50K") (0))
    ("Separated" ("United-States") (4) ("<=50K") (0))
    ("Widowed" ("United-States") (3) ("<=50K") (0)))
   ("England" ("Never-married" ("England") (1) ("<=50K") (0)))
   ("Cuba" ("Married-civ-spouse" ("Cuba") (1) ("<=50K") (0)))
   ("Canada" ("Divorced" ("Canada") (1) ("<=50K") (0)))
   ("Haiti" ("Widowed" ("Haiti") (1) ("<=50K") (0)))
   ("Honduras" ("Never-married" ("Honduras") (1) ("<=50K") (0)))
   ("Mexico" ("Married-civ-spouse" ("Mexico") (2) ("<=50K") (0)))))
 ((14 11)
  (ROOT ("D" ("United-States" ("United-States") (3) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (85) ("<=50K") (0))
    ("Cuba" ("Cuba") (1) ("<=50K") (0)) ("Canada" ("Canada") (1) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (1) ("<=50K") (0))
    ("Columbia" ("Columbia") (1) ("<=50K") (0))
    ("Germany" ("Germany") (3) ("<=50K") (0))
    ("Dominican-Republic" ("Dominican-Republic") (1) ("<=50K") (0)))
   ("B" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("C" ("United-States" ("United-States") (2) ("<=50K") (0)))))
 ((14 13)
  (ROOT
   ("C" ("United-States" ("United-States") (46) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (1) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0))
    ("Cambodia" ("Cambodia") (1) ("<=50K") (0)))
   ("D" ("United-States" ("United-States") (25) ("<=50K") (0))
    ("Guatemala" ("Guatemala") (1) ("<=50K") (0))
    ("Canada" ("Canada") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0)))
   ("A" ("United-States" ("United-States") (18) ("<=50K") (0))
    ("Puerto-Rico" ("Puerto-Rico") (1) ("<=50K") (0)))))
 ((2 12)
  (ROOT
   ("A" ("Private" ("Jamaica") (1) ("<=50K") (69))
    ("Self-emp-not-inc" ("United-States") (7) ("<=50K") (0))
    ("Federal-gov" ("United-States") (2) ("<=50K") (1))
    ("Local-gov" ("Mexico") (1) ("<=50K") (3))
    ("State-gov" ("United-States") (6) ("<=50K") (0))
    ("Self-emp-inc" ("Germany") (1) ("<=50K") (3)))
   ("D" ("Self-emp-inc" ("United-States") (2) ("<=50K") (0)))
   ("B" ("Private" ("United-States") (1) ("<=50K") (0)))
   ("C" ("Private" ("United-States") (2) ("<=50K") (0))
    ("Self-emp-not-inc" ("United-States") (1) ("<=50K") (0)))))
 ((9 14)
  (ROOT
   ("United-States" ("White" ("United-States") (79) ("<=50K") (0))
    ("Black" ("United-States") (9) ("<=50K") (0))
    ("Asian-Pac-Islander" ("United-States") (2) ("<=50K") (0))
    ("Other" ("United-States") (1) ("<=50K") (0))
    ("Amer-Indian-Eskimo" ("United-States") (1) ("<=50K") (0)))
   ("Taiwan" ("Asian-Pac-Islander" ("Taiwan") (1) ("<=50K") (0)))
   ("Peru" ("White" ("Peru") (1) ("<=50K") (0)))
   ("India" ("Asian-Pac-Islander" ("India") (1) ("<=50K") (0)))
   ("Mexico" ("White" ("Mexico") (1) ("<=50K") (0)))
   ("Germany" ("White" ("Germany") (1) ("<=50K") (0)))
   ("South" ("Asian-Pac-Islander" ("South") (1) ("<=50K") (0)))
   ("Guatemala" ("White" ("Guatemala") (1) ("<=50K") (0)))
   ("Philippines" ("Asian-Pac-Islander" ("Philippines") (1) ("<=50K") (0)))))
 ((13 5)
  (ROOT
   ("C" ("A" ("Mexico") (1) ("<=50K") (10))
    ("C" ("United-States") (16) ("<=50K") (1))
    ("D" ("Trinadad&Tobago") (1) ("<=50K") (7)))
   ("D" ("D" ("United-States") (12) ("<=50K") (0))
    ("C" ("United-States") (11) ("<=50K") (0))
    ("A" ("Vietnam") (1) ("<=50K") (4)))
   ("B" ("C" ("United-States") (14) ("<=50K") (0))
    ("D" ("United-States") (3) ("<=50K") (0))
    ("A" ("United-States") (6) ("<=50K") (1)))
   ("A" ("C" ("Greece") (1) ("<=50K") (3))
    ("A" ("United-States") (5) ("<=50K") (0))
    ("D" ("Mexico") (1) ("<=50K") (2)))))
 ((14 4)
  (ROOT ("Prof-school" ("United-States" ("United-States") (4) ("<=50K") (0)))
   ("Some-college" ("United-States" ("United-States") (17) ("<=50K") (0))
    ("Vietnam" ("Vietnam") (1) ("<=50K") (0)))
   ("HS-grad" ("United-States" ("United-States") (33) ("<=50K") (0))
    ("Columbia" ("Columbia") (1) ("<=50K") (0))
    ("Italy" ("Italy") (1) ("<=50K") (0)))
   ("Bachelors" ("United-States" ("United-States") (20) ("<=50K") (0)))
   ("Assoc-acdm" ("United-States" ("United-States") (5) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0)))
   ("10th" ("United-States" ("United-States") (4) ("<=50K") (0)))
   ("Assoc-voc" ("United-States" ("United-States") (2) ("<=50K") (0)))
   ("1st-4th" ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("Masters" ("United-States" ("United-States") (4) ("<=50K") (0)))
   ("11th" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("5th-6th" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("7th-8th" ("Cuba" ("Cuba") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (1) ("<=50K") (0)))
   ("Doctorate" ("United-States" ("United-States") (2) ("<=50K") (0)))))
 ((10 6)
  (ROOT
   ("Separated" ("Male" ("United-States") (2) ("<=50K") (0))
    ("Female" ("United-States") (2) ("<=50K") (0)))
   ("Never-married" ("Female" ("United-States") (14) ("<=50K") (1))
    ("Male" ("United-States") (18) ("<=50K") (1)))
   ("Married-civ-spouse" ("Male" ("United-States") (43) ("<=50K") (0))
    ("Female" ("United-States") (5) ("<=50K") (0)))
   ("Divorced" ("Male" ("United-States") (5) ("<=50K") (1))
    ("Female" ("Iran") (1) ("<=50K") (6)))
   ("Married-spouse-absent" ("Female" ("United-States") (1) ("<=50K") (0)))))
 ((14 9)
  (ROOT
   ("Black" ("United-States" ("United-States") (13) ("<=50K") (0))
    ("Haiti" ("Haiti") (2) ("<=50K") (0))
    ("Jamaica" ("Jamaica") (1) ("<=50K") (0)))
   ("White" ("United-States" ("United-States") (71) ("<=50K") (0))
    ("El-Salvador" ("El-Salvador") (1) ("<=50K") (0))
    ("Ireland" ("Ireland") (1) ("<=50K") (0))
    ("Mexico" ("Mexico") (2) ("<=50K") (0))
    ("Germany" ("Germany") (1) ("<=50K") (0))
    ("France" ("France") (1) ("<=50K") (0)))
   ("Asian-Pac-Islander" ("South" ("South") (1) ("<=50K") (0))
    ("India" ("India") (1) ("<=50K") (0))
    ("Cambodia" ("Cambodia") (1) ("<=50K") (0))
    ("Philippines" ("Philippines") (2) ("<=50K") (0)))
   ("Other" ("United-States" ("United-States") (1) ("<=50K") (0)))
   ("Amer-Indian-Eskimo"
    ("United-States" ("United-States") (1) ("<=50K") (0)))))
 ((5 1)
  (ROOT
   ("D" ("D" ("United-States") (7) ("<=50K") (0))
    ("C" ("United-States") (8) ("<=50K") (2))
    ("A" ("United-States") (5) ("<=50K") (2))
    ("B" ("United-States") (12) ("<=50K") (0)))
   ("A" ("A" ("United-States") (3) ("<=50K") (1))
    ("B" ("United-States") (7) ("<=50K") (0))
    ("C" ("United-States") (4) ("<=50K") (1))
    ("D" ("United-States") (3) ("<=50K") (0)))
   ("B" ("B" ("United-States") (9) ("<=50K") (1))
    ("C" ("United-States") (5) ("<=50K") (1))
    ("D" ("United-States") (6) ("<=50K") (1)))
   ("C" ("C" ("United-States") (5) ("<=50K") (0))
    ("D" ("United-States") (6) ("<=50K") (2))
    ("A" ("Puerto-Rico") (1) ("<=50K") (2))
    ("B" ("United-States") (6) ("<=50K") (0)))))
 ((2 9)
  (ROOT
   ("White" ("Self-emp-not-inc" ("United-States") (3) ("<=50K") (0))
    ("Self-emp-inc" ("United-States") (6) ("<=50K") (0))
    ("Private" ("United-States") (60) ("<=50K") (3))
    ("State-gov" ("United-States") (4) ("<=50K") (0))
    ("Local-gov" ("United-States") (8) ("<=50K") (0))
    ("Federal-gov" ("United-States") (4) ("<=50K") (0)))
   ("Other" ("Private" ("United-States") (1) ("<=50K") (0)))
   ("Black" ("Private" ("United-States") (4) ("<=50K") (0))
    ("Federal-gov" ("United-States") (1) ("<=50K") (0))
    ("Local-gov" ("United-States") (2) ("<=50K") (0)))
   ("Asian-Pac-Islander" ("Private" ("China") (1) ("<=50K") (2)))
   ("Amer-Indian-Eskimo" ("Private" ("United-States") (1) ("<=50K") (0)))))
 ((13 12)
  (ROOT
   ("A" ("C" ("Poland") (2) ("<=50K") (46))
    ("A" ("United-States") (19) ("<=50K") (3))
    ("D" ("United-States") (21) ("<=50K") (1)))
   ("C" ("C" ("United-States") (2) ("<=50K") (0))
    ("D" ("United-States") (1) ("<=50K") (0)))
   ("D" ("D" ("United-States") (1) ("<=50K") (0))
    ("A" ("United-States") (1) ("<=50K") (0)))
   ("B" ("A" ("United-States") (1) ("<=50K") (0))
    ("D" ("United-States") (2) ("<=50K") (0)))))
 ((1 3)
  (ROOT
   ("B" ("A" ("Thailand") (1) ("<=50K") (6))
    ("B" ("United-States") (3) ("<=50K") (0))
    ("C" ("United-States") (7) ("<=50K") (0))
    ("D" ("United-States") (6) ("<=50K") (0)))
   ("A" ("A" ("United-States") (9) ("<=50K") (0))
    ("B" ("United-States") (6) ("<=50K") (0))
    ("C" ("United-States") (2) ("<=50K") (0))
    ("D" ("United-States") (3) ("<=50K") (1)))
   ("D" ("B" ("United-States") (8) ("<=50K") (2))
    ("D" ("United-States") (6) ("<=50K") (1))
    ("C" ("United-States") (5) ("<=50K") (0))
    ("A" ("Puerto-Rico") (1) ("<=50K") (2)))
   ("C" ("B" ("United-States") (5) ("<=50K") (0))
    ("A" ("United-States") (7) ("<=50K") (0))
    ("D" ("United-States") (9) ("<=50K") (3))
    ("C" ("United-States") (7) ("<=50K") (0)))))
 ((12 2 14)
  (ROOT
   ("United-States"
    ("Private" ("A" ("United-States") (63) ("<=50K") (0))
     ("C" ("United-States") (2) ("<=50K") (0)))
    ("Self-emp-inc" ("A" ("United-States") (4) ("<=50K") (0)))
    ("Federal-gov" ("A" ("United-States") (3) ("<=50K") (0)))
    ("State-gov" ("A" ("United-States") (3) ("<=50K") (0)))
    ("Local-gov" ("A" ("United-States") (8) ("<=50K") (0))
     ("C" ("United-States") (1) ("<=50K") (0)))
    ("Self-emp-not-inc" ("A" ("United-States") (5) ("<=50K") (0))))
   ("El-Salvador" ("Private" ("A" ("El-Salvador") (1) ("<=50K") (0))))
   ("Mexico" ("Local-gov" ("A" ("Mexico") (1) ("<=50K") (0)))
    ("Private" ("A" ("Mexico") (2) ("<=50K") (0))))
   ("India" ("Private" ("A" ("India") (1) ("<=50K") (0))))
   ("England" ("Private" ("A" ("England") (1) ("<=50K") (0))))
   ("China" ("Private" ("A" ("China") (1) ("<=50K") (0))))
   ("France" ("Private" ("A" ("France") (1) ("<=50K") (0))))
   ("Peru" ("Private" ("A" ("Peru") (1) ("<=50K") (0))))
   ("Germany" ("Private" ("A" ("Germany") (1) ("<=50K") (0))))
   ("Taiwan" ("Private" ("A" ("Taiwan") (1) ("<=50K") (0))))))) )) 
(defvar results (quote 

(0.98380506 0.9834 0.9833 0.9838 0.984 0.9819 0.9827 0.9851 0.9848 0.9837
 0.9841 0.9846 0.9837 0.9861 0.9847 0.981 0.9837 0.9839 0.9827 0.9837 0.9852) )) 
;;;;;;;;;;;;;

; Wich features are numeric? 0: not, 1: yes. *(not yet implemented)
(defvar *num-fetures* '(1 3 5 11 12 13))
; Total features *(not yet implemented)
(defvar *total-fetures* '14)
(defvar *min-fetures-sample* '2)
(defvar *max-fetures-sample* '5)
; Targets? 
(defvar *targets* '("<=50K" ">50K"))

; Model parameters.

; Number os trees in the forest:
(defvar *NTrees* 20)
; How much samples will be used to build the trees?
(defvar *NSamples* 100)
; To prune the worst trees with low rating accuracy.
; Prune below THPrec.
(defvar *THPrec* 0.97)

; Test rounds 
(defvar *TRounds* 20)
; Load the datasets to memory
(defvar *TSamples_train* 30000)
(defvar *TSamples_test* 10000)

; 16280 dataset.test.csv
; 32561 dataset.training.csv
; 48841 total
; Without samples with missing data:
; 15059 dataset.test.csv
; 30162 dataset.training.csv
; 45221 total

;EOF